!> Process for computing windblown dust emissions
!!
!! This module provides the dust process interface for the CATChem library.
!! The interface leverages CATChem's core infrastructure for data marshaling and process management.
!! All algorithmic calculations are performed in separate scheme modules.
!!
!! DIAGNOSTIC INTERFACE:
!! The compute_scheme functions support optional diagnostic parameters. When diagnostics are
!! enabled in the configuration, these parameters are passed to capture emission/tendency data.
!! When diagnostics are disabled, the scheme calls use the original interface without diagnostics.
!! This approach maintains backward compatibility while providing flexible diagnostic capabilities.
!!
!! This code was generated by the CATChem Process Generator.
!! Generation date: 2025-09-09T14:29:24.549662
!! Configuration: dust
!!
!! @author CATChem Process Generator
!! @version 1.0.0

module ProcessDustInterface_Mod

   ! Core CATChem infrastructure
   use precision_mod, only: fp
   use ProcessInterface_Mod, only: ProcessInterface, ColumnProcessInterface
   use StateManager_Mod, only: StateManagerType
   use GridManager_Mod, only: GridManagerType
   use error_mod, only: CC_SUCCESS, CC_FAILURE, CC_Error, CC_Warning, ErrorManagerType
   use DiagnosticManager_Mod, only: DiagnosticManagerType
   use DiagnosticInterface_Mod, only: DiagnosticRegistryType, DiagnosticFieldType, DiagnosticDataType
   use VirtualColumn_Mod, only: VirtualColumnType, VirtualMetType

   ! Core utilities (leverage existing infrastructure)
   use ConfigManager_Mod, only: ConfigManagerType
   use ChemState_Mod, only: ChemStateType
   use MetState_Mod, only: MetStateType

   ! Common utilities - unified configuration
   use DustCommon_Mod, only: DustProcessConfig

   ! Scheme modules
   use DustScheme_FENGSHA_Mod, only: compute_fengsha
   use DustScheme_GINOUX_Mod, only: compute_ginoux

   implicit none
   private

   public :: ProcessDustInterface

   !> Main dust process interface type - extends core ColumnProcessInterface   !!
   !! This type leverages CATChem's core ColumnProcessInterface infrastructure for column
   !! virtualization, focusing only on process-specific configuration and scheme management.
   !! All boilerplate infrastructure and column processing is handled by the base class.
   type, extends(ColumnProcessInterface) :: ProcessDustInterface
      private

      ! Unified process configuration (bridges ConfigManager to process-specific config)
      type(DustProcessConfig) :: process_config

      ! Process utilities (leverage core infrastructure)
      type(ChemStateType), pointer :: chem_state => null()
      type(MetStateType), pointer :: met_state => null()
      ! Note: state_manager pointer removed as it was never used

      ! Process-specific diagnostic indices (base class handles storage)
      integer :: diag_total_dust_emission_idx = -1

      ! Column-level diagnostic storage for interfacing with DiagManager
      ! These are allocated per-column during processing and can be used to
      ! accumulate data for DiagManager updates
      real(fp), allocatable :: column_total_dust_emission              ! scalar - per column

      ! Scheme-specific diagnostic storage (shared across all schemes that use them)
      real(fp), allocatable :: column_dust_horizontal_flux              ! scheme-specific scalar - per column
      real(fp), allocatable :: column_dust_moisture_correction              ! scheme-specific scalar - per column
      real(fp), allocatable :: column_dust_effective_threshold              ! scheme-specific scalar - per column

   contains
      ! Required ProcessInterface implementations
      procedure :: init => process_init
      procedure :: run => process_run
      procedure :: finalize => process_finalize
      procedure :: parse_process_config => parse_dust_config

      ! Required ColumnProcessInterface implementations
      procedure :: init_column_processing => init_column_processing
      procedure :: run_column => run_column
      procedure :: finalize_column_processing => finalize_column_processing

      ! ProcessInterface capability registration
      procedure :: get_required_met_fields => get_required_met_fields
      procedure :: get_required_diagnostic_fields => get_required_diagnostic_fields

      ! Process-specific implementations (column virtualization)
      procedure, private :: run_active_scheme_column
      procedure, private :: run_fengsha_scheme_column
      procedure, private :: run_ginoux_scheme_column

      ! Diagnostic procedures (override base class method)
      procedure :: register_diagnostics => register_process_diagnostics
      procedure, private :: register_process_diagnostics
      procedure, private :: calculate_and_update_diagnostics

   end type ProcessDustInterface

contains

   !> Initialize the dust process
   !!
   !! Leverages ProcessInterface base class for common initialization tasks.
   !! Only handles process-specific configuration and scheme setup.
   subroutine process_init(this, container, rc)
      class(ProcessDustInterface), intent(inout) :: this
      type(StateManagerType), intent(inout) :: container
      integer, intent(out) :: rc

      type(ErrorManagerType), pointer :: error_manager
      type(GridManagerType), pointer :: grid_mgr

      rc = CC_SUCCESS

      ! Get error manager
      error_manager => container%get_error_manager()

      ! Get grid manager for diagnostic allocation
      grid_mgr => container%get_grid_manager()

      ! Initialize column processing capabilities
      call this%init_column_processing(container, rc)
      if (rc /= CC_SUCCESS) return

      ! Set process-specific name and info
      this%name = 'dust'
      this%version = '1.0.0'
      this%description = 'Process for computing windblown dust emissions'

      ! Parse process-specific configuration using unified approach
      call this%parse_process_config(container, error_manager, rc)
      if (rc /= CC_SUCCESS) then
         return
      end if

      ! Get state pointers from container (needed for species loading)
      this%chem_state => container%get_chem_state_ptr()
      this%met_state => container%get_met_state_ptr()

      ! Load species from ChemState based on is_dust property
      call this%process_config%load_species_from_chem_state(this%chem_state, error_manager)
      ! Note: Error handling managed by error_manager internally

      ! Validate the configuration with StateManager
      call this%process_config%validate(container, error_manager)
      ! Note: validate doesn't return rc, but error_manager tracks errors

      ! Register diagnostics for this process (only if diagnostics enabled)
      call this%register_diagnostics(container, rc)
      if (rc /= CC_SUCCESS) then
         return
      end if

      ! Allocate diagnostic class members if diagnostics are enabled
      if (this%process_config%dust_config%diagnostics) then
         ! Allocate common diagnostic fields (used by all schemes)
         ! Scalar diagnostic
         allocate(this%column_total_dust_emission)
         this%column_total_dust_emission = 0.0_fp

         ! Allocate and initialize scheme-specific diagnostic fields based on selected scheme
         select case (this%process_config%dust_config%scheme)
          case ("fengsha")
            ! Scheme-specific diagnostics for fengsha
            ! Scalar diagnostic
            allocate(this%column_dust_horizontal_flux)
            this%column_dust_horizontal_flux = 0.0_fp
            ! Scalar diagnostic
            allocate(this%column_dust_moisture_correction)
            this%column_dust_moisture_correction = 0.0_fp
            ! Scalar diagnostic
            allocate(this%column_dust_effective_threshold)
            this%column_dust_effective_threshold = 0.0_fp
          case ("ginoux")
            ! Scheme-specific diagnostics for ginoux
            ! Scalar diagnostic
            allocate(this%column_dust_horizontal_flux)
            this%column_dust_horizontal_flux = 0.0_fp
            ! Scalar diagnostic
            allocate(this%column_dust_moisture_correction)
            this%column_dust_moisture_correction = 0.0_fp
            ! Scalar diagnostic
            allocate(this%column_dust_effective_threshold)
            this%column_dust_effective_threshold = 0.0_fp
          case default
            ! No scheme-specific diagnostics for unknown schemes
         end select
      end if

   end subroutine process_init

   !> Run the dust process
   !!
   !! This method implements the main ProcessInterface run method.
   !! For ColumnProcessInterface processes, the actual column iteration is handled
   !! by ProcessManager, so this method serves as a placeholder for any 3D operations
   !! that might be needed before or after column processing.
   subroutine process_run(this, container, rc)
      class(ProcessDustInterface), intent(inout) :: this
      type(StateManagerType), intent(inout) :: container
      integer, intent(out) :: rc

      rc = CC_SUCCESS

      ! Check if process is active
      if (.not. this%process_config%is_active) then
         return
      end if

      ! For ColumnProcessInterface processes, the ProcessManager handles column iteration
      ! and calls run_column() for each virtual column. This method is mainly a placeholder
      ! for any global 3D operations that need to happen before/after column processing.

      ! Currently no global 3D operations needed for dust process
      ! All processing happens in run_column() method

   end subroutine process_run

   !> Finalize the dust process
   subroutine process_finalize(this, rc)
      class(ProcessDustInterface), intent(inout) :: this
      integer, intent(out) :: rc

      rc = CC_SUCCESS

      ! Finalize column processing
      call this%finalize_column_processing(rc)
      if (rc /= CC_SUCCESS) return

      ! Deallocate diagnostic class members
      if (allocated(this%column_total_dust_emission)) deallocate(this%column_total_dust_emission)
      ! Deallocate scheme-specific diagnostic fields (only deallocate unique fields once)
      if (allocated(this%column_dust_horizontal_flux)) deallocate(this%column_dust_horizontal_flux)
      if (allocated(this%column_dust_moisture_correction)) deallocate(this%column_dust_moisture_correction)
      if (allocated(this%column_dust_effective_threshold)) deallocate(this%column_dust_effective_threshold)

      ! Finalize unified configuration
      call this%process_config%finalize()

   end subroutine process_finalize

   !> Parse process configuration using unified approach
   !! This function bridges the ConfigManager YAML structure to process-specific configuration
   subroutine parse_dust_config(this, state_manager, error_manager, rc)
      class(ProcessDustInterface), intent(inout) :: this
      type(StateManagerType), intent(in) :: state_manager
      type(ErrorManagerType), intent(inout) :: error_manager
      integer, intent(out) :: rc

      type(ConfigManagerType), pointer :: config_manager

      rc = CC_SUCCESS

      ! Get configuration manager from state manager
      ! TODO: StateManager needs to provide ConfigManagerType access
      ! For now, this will need to be updated when StateManager interface is enhanced
      ! config_manager => state_manager%get_config_manager()

      ! Use the unified configuration loader from DustCommon_Mod
      ! This handles the complexity of parsing hierarchical YAML into process-specific types
      call this%process_config%load_from_config(config_manager, error_manager)
      ! Note: Error handling managed by error_manager internally

      ! Process is now configured - the unified config contains all scheme-specific settings

   end subroutine parse_dust_config

   !========================================================================
   ! Column Processing Interface Implementation
   !========================================================================

   !> Initialize column processing for dust
   !!
   !! This method sets up the column processing infrastructure for the process.
   !! The base class ColumnProcessInterface handles the actual column virtualization.
   subroutine init_column_processing(this, container, rc)
      class(ProcessDustInterface), intent(inout) :: this
      type(StateManagerType), intent(inout) :: container
      integer, intent(out) :: rc

      rc = CC_SUCCESS

      ! Enable column processing and set batch size for optimal performance
      call this%enable_column_processing()
      call this%set_column_batch_size(50)  ! Process 50 columns at a time

      ! Any process-specific column processing setup would go here
      ! For dust, no additional setup is needed

   end subroutine init_column_processing

   !> Process a single virtual column for dust
   !!
   !! This is the core column processing method where the actual atmospheric process
   !! calculations happen for a single column. The base class handles column
   !! virtualization and calls this method for each virtual column.
   subroutine run_column(this, column, container, rc)
      class(ProcessDustInterface), intent(inout) :: this
      type(VirtualColumnType), intent(inout) :: column
      type(StateManagerType), intent(inout) :: container
      integer, intent(out) :: rc

      rc = CC_SUCCESS

      ! Check if process is active
      if (.not. this%process_config%is_active) return

      ! Delegate to the active scheme for column processing
      call this%run_active_scheme_column(column, rc)

      ! Calculate and update diagnostics if enabled
      if (this%process_config%dust_config%diagnostics .and. rc == CC_SUCCESS) then
         call this%calculate_and_update_diagnostics(column, container, rc)
      end if

   end subroutine run_column

   !> Finalize column processing for dust
   !!
   !! Clean up any column processing resources.
   subroutine finalize_column_processing(this, rc)
      class(ProcessDustInterface), intent(inout) :: this
      integer, intent(out) :: rc

      rc = CC_SUCCESS

      ! Clean up column processing
      call this%disable_column_processing()

      ! Any process-specific cleanup would go here

   end subroutine finalize_column_processing

   !> Run the active scheme for a single virtual column
   !!
   !! This method adapts the existing scheme methods to work with virtual columns
   !! instead of state manager column indices.
   subroutine run_active_scheme_column(this, column, rc)
      class(ProcessDustInterface), intent(inout) :: this
      type(VirtualColumnType), intent(inout) :: column
      integer, intent(out) :: rc

      rc = CC_SUCCESS

      ! Delegate to appropriate scheme using unified config
      select case (trim(this%process_config%dust_config%scheme))
       case ('fengsha')
         call this%run_fengsha_scheme_column(column, rc)
       case ('ginoux')
         call this%run_ginoux_scheme_column(column, rc)
       case default
         rc = CC_FAILURE
      end select

   end subroutine run_active_scheme_column

   !> Run the fengsha scheme for a single virtual column
   subroutine run_fengsha_scheme_column(this, column, rc)
      class(ProcessDustInterface), intent(inout) :: this
      type(VirtualColumnType), intent(inout) :: column
      integer, intent(out) :: rc

      ! Local variables for scheme calculation
      type(VirtualMetType), pointer :: met => null()  ! Pointer to meteorological data
      ! Meteorological fields
      real(fp), allocatable :: island(:)
      real(fp), allocatable :: ustar(:)
      real(fp), allocatable :: lwi(:)
      real(fp), allocatable :: gvf(:)
      real(fp), allocatable :: lai(:)
      real(fp), allocatable :: frocean(:)
      real(fp), allocatable :: clayfrac(:)
      real(fp), allocatable :: sandfrac(:)
      real(fp), allocatable :: frsno(:)
      real(fp), allocatable :: rdrag(:)
      real(fp), allocatable :: ssm(:)
      real(fp), allocatable :: ustar_threshold(:)
      real(fp), allocatable :: species_conc(:,:)
      real(fp), allocatable :: species_tendencies(:,:)
      integer :: n_species, n_levels, n_chem, n_emis, i, k
      integer, allocatable :: species_indices(:)

      rc = CC_SUCCESS

      ! Get dimensions from virtual column
      n_levels = 1  ! Surface-only processing

      ! Get dust species information from process configuration
      n_species = this%process_config%dust_config%n_species
      if (n_species <= 0) then
         return
      end if

      ! Get species indices directly from configuration (pre-computed)
      allocate(species_indices(n_species))
      species_indices(1:n_species) = this%process_config%dust_config%species_indices(1:n_species)

      ! Allocate arrays
      allocate(species_conc(1, n_species))
      allocate(species_tendencies(1, n_species))
      ! Allocate meteorological field arrays based on field type and process configuration
      allocate(island(1))  ! Surface field - always scalar
      allocate(ustar(1))  ! Surface field - always scalar
      allocate(lwi(1))  ! Surface field - always scalar
      allocate(gvf(1))  ! Surface field - always scalar
      allocate(lai(1))  ! Surface field - always scalar
      allocate(frocean(1))  ! Surface field - always scalar
      allocate(clayfrac(1))  ! Surface field - always scalar
      allocate(sandfrac(1))  ! Surface field - always scalar
      allocate(frsno(1))  ! Surface field - always scalar
      allocate(rdrag(1))  ! Surface field - always scalar
      allocate(ssm(1))  ! Surface field - always scalar
      allocate(ustar_threshold(1))  ! Surface field - always scalar
      species_tendencies = 0.0_fp

      ! Get meteorological data pointer from virtual column (VirtualMet pattern)
      met => column%get_met()

      ! Extract required fields from met pointer based on field type and processing mode
      island(1) = met%IsLand  ! Surface field - scalar access
      ustar(1) = met%USTAR  ! Surface field - scalar access
      lwi(1) = met%LWI  ! Surface field - scalar access
      gvf(1) = met%GVF  ! Surface field - scalar access
      lai(1) = met%LAI  ! Surface field - scalar access
      frocean(1) = met%FROCEAN  ! Surface field - scalar access
      clayfrac(1) = met%CLAYFRAC  ! Surface field - scalar access
      sandfrac(1) = met%SANDFRAC  ! Surface field - scalar access
      frsno(1) = met%FRSNO  ! Surface field - scalar access
      rdrag(1) = met%RDRAG  ! Surface field - scalar access
      ssm(1) = met%SSM  ! Surface field - scalar access
      ustar_threshold(1) = met%USTAR_THRESHOLD  ! Surface field - scalar access

      ! Get species concentrations from virtual column
      ! Surface-only processing - get surface level concentrations
      do i = 1, n_species
         species_conc(1, i) = column%get_chem_field(species_indices(i), 1)
      end do


      ! Call the science scheme with optional diagnostic parameters
      ! Note: fengsha uses the following diagnostic fields (if diagnostics enabled):
      ! - total_dust_emission (Total dust emissions for all species)
      if (this%process_config%dust_config%diagnostics) then
         ! Call with diagnostic outputs enabled
         call compute_fengsha( &
            n_levels, &
            n_species, &
            this%process_config%fengsha_config, &
            island, &
            ustar, &
            lwi, &
            gvf, &
            lai, &
            frocean, &
            clayfrac, &
            sandfrac, &
            frsno, &
            rdrag, &
            ssm, &
            ustar_threshold, &
            species_conc, &
            species_tendencies, &
            this%column_total_dust_emission, &
            this%column_dust_horizontal_flux, &
            this%column_dust_moisture_correction, &
            this%column_dust_effective_threshold &
            )
      else
         ! Call without diagnostic outputs (optional parameters not passed)
         call compute_fengsha( &
            n_levels, &
            n_species, &
            this%process_config%fengsha_config, &
            island, &
            ustar, &
            lwi, &
            gvf, &
            lai, &
            frocean, &
            clayfrac, &
            sandfrac, &
            frsno, &
            rdrag, &
            ssm, &
            ustar_threshold, &
            species_conc, &
            species_tendencies &
            )
      end if

      ! Apply tendencies back to virtual column
      ! Surface-only processing - apply tendencies to surface level only
      do i = 1, n_species
         call column%set_chem_field(1, species_indices(i), &
            species_conc(1, i) + species_tendencies(1, i))
      end do

   end subroutine run_fengsha_scheme_column

   !> Run the ginoux scheme for a single virtual column
   subroutine run_ginoux_scheme_column(this, column, rc)
      class(ProcessDustInterface), intent(inout) :: this
      type(VirtualColumnType), intent(inout) :: column
      integer, intent(out) :: rc

      ! Local variables for scheme calculation
      type(VirtualMetType), pointer :: met => null()  ! Pointer to meteorological data
      ! Meteorological fields
      real(fp), allocatable :: frlake(:)
      real(fp), allocatable :: gwettop(:)
      real(fp), allocatable :: u10m(:)
      real(fp), allocatable :: v10m(:)
      real(fp), allocatable :: ssm(:)
      real(fp), allocatable :: species_conc(:,:)
      real(fp), allocatable :: species_tendencies(:,:)
      integer :: n_species, n_levels, n_chem, n_emis, i, k
      integer, allocatable :: species_indices(:)

      rc = CC_SUCCESS

      ! Get dimensions from virtual column
      n_levels = 1  ! Surface-only processing

      ! Get dust species information from process configuration
      n_species = this%process_config%dust_config%n_species
      if (n_species <= 0) then
         return
      end if

      ! Get species indices directly from configuration (pre-computed)
      allocate(species_indices(n_species))
      species_indices(1:n_species) = this%process_config%dust_config%species_indices(1:n_species)

      ! Allocate arrays
      allocate(species_conc(1, n_species))
      allocate(species_tendencies(1, n_species))
      ! Allocate meteorological field arrays based on field type and process configuration
      allocate(frlake(1))  ! Surface field - always scalar
      allocate(gwettop(1))  ! Surface field - always scalar
      allocate(u10m(1))  ! Surface field - always scalar
      allocate(v10m(1))  ! Surface field - always scalar
      allocate(ssm(1))  ! Surface field - always scalar
      species_tendencies = 0.0_fp

      ! Get meteorological data pointer from virtual column (VirtualMet pattern)
      met => column%get_met()

      ! Extract required fields from met pointer based on field type and processing mode
      frlake(1) = met%FRLAKE  ! Surface field - scalar access
      gwettop(1) = met%GWETTOP  ! Surface field - scalar access
      u10m(1) = met%U10M  ! Surface field - scalar access
      v10m(1) = met%V10M  ! Surface field - scalar access
      ssm(1) = met%SSM  ! Surface field - scalar access

      ! Get species concentrations from virtual column
      ! Surface-only processing - get surface level concentrations
      do i = 1, n_species
         species_conc(1, i) = column%get_chem_field(species_indices(i), 1)
      end do


      ! Call the science scheme with optional diagnostic parameters
      ! Note: ginoux uses the following diagnostic fields (if diagnostics enabled):
      ! - total_dust_emission (Total dust emissions for all species)
      if (this%process_config%dust_config%diagnostics) then
         ! Call with diagnostic outputs enabled
         call compute_ginoux( &
            n_levels, &
            n_species, &
            this%process_config%ginoux_config, &
            frlake, &
            gwettop, &
            u10m, &
            v10m, &
            ssm, &
            species_conc, &
            species_tendencies, &
            this%column_total_dust_emission, &
            this%column_dust_horizontal_flux, &
            this%column_dust_moisture_correction, &
            this%column_dust_effective_threshold &
            )
      else
         ! Call without diagnostic outputs (optional parameters not passed)
         call compute_ginoux( &
            n_levels, &
            n_species, &
            this%process_config%ginoux_config, &
            frlake, &
            gwettop, &
            u10m, &
            v10m, &
            ssm, &
            species_conc, &
            species_tendencies &
            )
      end if

      ! Apply tendencies back to virtual column
      ! Surface-only processing - apply tendencies to surface level only
      do i = 1, n_species
         call column%set_chem_field(1, species_indices(i), &
            species_conc(1, i) + species_tendencies(1, i))
      end do

   end subroutine run_ginoux_scheme_column



   !> Get required meteorological fields for this process
   function get_required_met_fields(this) result(field_names)
      class(ProcessDustInterface), intent(in) :: this
      character(len=32), allocatable :: field_names(:)

      ! Get scheme-specific fields based on selected scheme
      select case (trim(this%process_config%dust_config%scheme))
       case ('fengsha')
         allocate(field_names(12))
         field_names(1) = 'IsLand'
         field_names(2) = 'USTAR'
         field_names(3) = 'LWI'
         field_names(4) = 'GVF'
         field_names(5) = 'LAI'
         field_names(6) = 'FROCEAN'
         field_names(7) = 'CLAYFRAC'
         field_names(8) = 'SANDFRAC'
         field_names(9) = 'FRSNO'
         field_names(10) = 'RDRAG'
         field_names(11) = 'SSM'
         field_names(12) = 'USTAR_THRESHOLD'
       case ('ginoux')
         allocate(field_names(5))
         field_names(1) = 'FRLAKE'
         field_names(2) = 'GWETTOP'
         field_names(3) = 'U10M'
         field_names(4) = 'V10M'
         field_names(5) = 'SSM'
       case default
         allocate(field_names(0))
      end select

   end function get_required_met_fields

   !> Get required diagnostic fields for this process
   function get_required_diagnostic_fields(this) result(field_names)
      class(ProcessDustInterface), intent(in) :: this
      character(len=32), allocatable :: field_names(:)

      allocate(field_names(1))
      field_names(1) = 'total_dust_emission'

   end function get_required_diagnostic_fields

   !> Register diagnostic fields with the DiagnosticManager

   subroutine register_process_diagnostics(this, container, rc)
      use DiagnosticInterface_Mod, only: DiagnosticRegistryType, DIAG_REAL_2D, DIAG_REAL_3D

      class(ProcessDustInterface), intent(inout) :: this
      type(StateManagerType), intent(inout) :: container
      integer, intent(out) :: rc

      type(DiagnosticManagerType), pointer :: diag_mgr
      type(DiagnosticRegistryType), pointer :: registry
      type(GridManagerType), pointer :: grid_mgr
      character(len=32) :: selected_scheme
      integer :: nx, ny, nz
      integer :: dims_2d(2)

      rc = CC_SUCCESS

      ! Only register diagnostics if enabled in config
      if (.not. this%process_config%dust_config%diagnostics) then
         return
      endif

      ! Get managers
      diag_mgr => container%get_diagnostic_manager()
      grid_mgr => container%get_grid_manager()

      ! Register this process with diagnostic manager (only once per process)
      call diag_mgr%register_process('dust', rc)
      if (rc /= CC_SUCCESS) return

      ! Get the process registry for registering individual diagnostics
      call diag_mgr%get_process_registry('dust', registry, rc)
      if (rc /= CC_SUCCESS) return

      ! Get grid dimensions
      call grid_mgr%get_shape(nx, ny, nz)
      dims_2d = [nx, ny]


      ! Register total_dust_emission
      call this%register_diagnostic_field(registry, 'total_dust_emission', &
         'Total dust emissions for all species', &
         'kg/m2/s', DIAG_REAL_2D, &
         'dust', dims_2d, rc)
      if (rc /= CC_SUCCESS) return

      ! Get selected scheme
      selected_scheme = trim(this%process_config%dust_config%scheme)

      ! Register scheme-specific diagnostics based on selected scheme
      select case (selected_scheme)

       case ('fengsha')
         ! Register fengsha-specific diagnostics
         call this%register_diagnostic_field(registry, 'dust_horizontal_flux', &
            'Total horizontal flux - Q', &
            'kg/m2/s', DIAG_REAL_2D, &
            'dust', dims_2d, rc)
         if (rc /= CC_SUCCESS) return

         call this%register_diagnostic_field(registry, 'dust_moisture_correction', &
            'Moisture Correction - H', &
            'dimensionless', DIAG_INTEGER_2D, &
            'dust', dims_2d, rc)
         if (rc /= CC_SUCCESS) return

         call this%register_diagnostic_field(registry, 'dust_effective_threshold', &
            'Effective Dust threshold friction velocity: u_thres * H / R', &
            'm/s', DIAG_REAL_2D, &
            'dust', dims_2d, rc)
         if (rc /= CC_SUCCESS) return

       case ('ginoux')
         ! Register ginoux-specific diagnostics
         call this%register_diagnostic_field(registry, 'dust_horizontal_flux', &
            'Total horizontal flux - Q', &
            'kg/m2/s', DIAG_REAL_2D, &
            'dust', dims_2d, rc)
         if (rc /= CC_SUCCESS) return

         call this%register_diagnostic_field(registry, 'dust_moisture_correction', &
            'Moisture Correction - H', &
            'dimensionless', DIAG_INTEGER_2D, &
            'dust', dims_2d, rc)
         if (rc /= CC_SUCCESS) return

         call this%register_diagnostic_field(registry, 'dust_effective_threshold', &
            'Effective Dust threshold friction velocity: u_thres * H / R', &
            'm/s', DIAG_REAL_2D, &
            'dust', dims_2d, rc)
         if (rc /= CC_SUCCESS) return

       case default
         ! Unknown scheme - only register common diagnostics
         ! (already done above)

      end select

   end subroutine register_process_diagnostics

   !> Calculate and update all diagnostic fields for this process
   !!
   !! With the new flexible column-level design, diagnostics are calculated directly by the
   !! science schemes for each column and passed to this method for aggregation or output.
   !! This approach uses dimension inference to reduce 2D->scalar and 3D->1D for column processing.
   subroutine calculate_and_update_diagnostics(this, column, container, rc)
      class(ProcessDustInterface), intent(inout) :: this
      type(VirtualColumnType), intent(in) :: column
      type(StateManagerType), intent(inout) :: container
      integer, intent(out) :: rc

      integer :: i_col, j_col  ! Column grid position
      character(len=64) :: selected_scheme

      rc = CC_SUCCESS

      ! Skip if diagnostics not enabled
      if (.not. this%process_config%dust_config%diagnostics) return

      ! Get column grid position (x, y indices)
      call column%get_position(i_col, j_col)

      ! Update common diagnostic fields (used by all schemes)
      ! Scalar diagnostic field
      call this%update_scalar_diagnostic_column('total_dust_emission', &
         this%column_total_dust_emission, &
         i_col, j_col, container, rc)
      if (rc /= CC_SUCCESS) return
      ! Update scheme-specific diagnostic fields based on active scheme
      selected_scheme = trim(this%process_config%dust_config%scheme)

      select case (selected_scheme)
       case ("fengsha")
         ! Update scalar diagnostics (map to 2D global fields)
         if (allocated(this%column_dust_horizontal_flux)) then
            call this%update_scalar_diagnostic_column('dust_horizontal_flux', &
               this%column_dust_horizontal_flux, &
               i_col, j_col, container, rc)
            if (rc /= CC_SUCCESS) return
         end if

         ! Update scalar diagnostics (map to 2D global fields)
         if (allocated(this%column_dust_moisture_correction)) then
            call this%update_scalar_diagnostic_column('dust_moisture_correction', &
               this%column_dust_moisture_correction, &
               i_col, j_col, container, rc)
            if (rc /= CC_SUCCESS) return
         end if

         ! Update scalar diagnostics (map to 2D global fields)
         if (allocated(this%column_dust_effective_threshold)) then
            call this%update_scalar_diagnostic_column('dust_effective_threshold', &
               this%column_dust_effective_threshold, &
               i_col, j_col, container, rc)
            if (rc /= CC_SUCCESS) return
         end if

       case ("ginoux")
         ! Update scalar diagnostics (map to 2D global fields)
         if (allocated(this%column_dust_horizontal_flux)) then
            call this%update_scalar_diagnostic_column('dust_horizontal_flux', &
               this%column_dust_horizontal_flux, &
               i_col, j_col, container, rc)
            if (rc /= CC_SUCCESS) return
         end if

         ! Update scalar diagnostics (map to 2D global fields)
         if (allocated(this%column_dust_moisture_correction)) then
            call this%update_scalar_diagnostic_column('dust_moisture_correction', &
               this%column_dust_moisture_correction, &
               i_col, j_col, container, rc)
            if (rc /= CC_SUCCESS) return
         end if

         ! Update scalar diagnostics (map to 2D global fields)
         if (allocated(this%column_dust_effective_threshold)) then
            call this%update_scalar_diagnostic_column('dust_effective_threshold', &
               this%column_dust_effective_threshold, &
               i_col, j_col, container, rc)
            if (rc /= CC_SUCCESS) return
         end if

      end select

   end subroutine calculate_and_update_diagnostics


end module ProcessDustInterface_Mod
