!> Process for computing windblown dust emissions
!!
!! This module provides the dust process interface for the CATChem library.
!! The interface leverages CATChem's core infrastructure for data marshaling and process management.
!! All algorithmic calculations are performed in separate scheme modules.
!!
!! This code was generated by the CATChem Process Generator.
!! Generation date: 
!! Configuration: dust
!!
!! @author CATChem Process Generator
!! @version 

module ProcessDustInterface_Mod

   ! Core CATChem infrastructure
   use precision_mod, only: fp
   use ProcessInterface_Mod, only: ProcessInterface, ColumnProcessInterface
   use StateManager_Mod, only: StateManagerType
   use error_mod, only: CC_SUCCESS, CC_FAILURE, ErrorManagerType
   use DiagnosticManager_Mod, only: DiagnosticManagerType

   ! Core utilities (leverage existing infrastructure)
   use ChemSpeciesUtils_Mod, only: ChemSpeciesUtilsType
   use UnitConversion_Mod, only: UnitConverterType
   use MetFieldUtils_Mod, only: MetFieldUtilsType
   use ConfigManager_Mod, only: ConfigDataType

   ! Scheme modules
   use fengsha_scheme_mod, only: compute_fengsha, fengsha_params_t
   use ginoux_scheme_mod, only: compute_ginoux, ginoux_params_t

   implicit none
   private

   public :: ProcessDustInterface

   !> Main dust process interface type - extends core ProcessInterface
   !!
   !! This type leverages CATChem's core ProcessInterface infrastructure, focusing only
   !! on process-specific configuration and scheme management. All boilerplate infrastructure
   !! is handled by the base class.
   type, extends(ProcessInterface) :: ProcessDustInterface
      private

      ! Process-specific configuration
      character(len=64) :: active_scheme = 'fengsha'

      ! Scheme configuration parameters (lightweight delegation)
      type(fengsha_params_t) :: config_fengsha
      type(ginoux_params_t) :: config_ginoux

      ! Process utilities (leverage core infrastructure)
      type(ChemSpeciesUtilsType) :: species_utils
      type(UnitConverterType) :: unit_converter
      type(MetFieldUtilsType) :: met_utils

      ! Process-specific diagnostic indices (base class handles storage)
      integer :: diag_total_dust_emission_idx = -1

   contains
      ! Required ProcessInterface implementations
      procedure :: init => process_init
      procedure :: run => process_run
      procedure :: finalize => process_finalize

      ! ProcessInterface capability registration (simplified)
      procedure :: get_required_met_fields => get_required_met_fields
      procedure :: get_required_diagnostic_fields => get_required_diagnostic_fields

      ! Process-specific implementations
      procedure, private :: configure_schemes
      procedure, private :: run_active_scheme
      procedure, private :: run_fengsha_scheme
      procedure, private :: run_ginoux_scheme


   end type ProcessDustInterface

contains

   !> Initialize the dust process
   !!
   !! Leverages ProcessInterface base class for common initialization tasks.
   !! Only handles process-specific configuration and scheme setup.
   subroutine process_init(this, config_data, state_manager, error_manager)
      class(ProcessDustInterface), intent(inout) :: this
      type(ConfigDataType), intent(in) :: config_data
      type(StateManagerType), intent(in) :: state_manager
      type(ErrorManagerType), intent(inout) :: error_manager

      integer :: rc

      ! Call base class initialization (handles common infrastructure)
      call this%ProcessInterface%init(config_data, state_manager, error_manager)
      if (error_manager%has_error()) return

      ! Set process-specific name and info
      call this%set_name('dust')
      call this%set_version('')
      call this%set_description('Process for computing windblown dust emissions')

      ! Parse process-specific configuration
      call this%parse_process_config(config_data, error_manager)
      if (error_manager%has_error()) return

      ! Configure schemes
      call this%configure_schemes(config_data, error_manager)
      if (error_manager%has_error()) return

      ! Initialize utility helpers
      call this%species_utils%init(state_manager, error_manager)
      call this%unit_converter%init(error_manager)
      call this%met_utils%init(state_manager, error_manager)
      if (error_manager%has_error()) return

   end subroutine process_init

   !> Run the dust process
   !!
   !! Simplified implementation leveraging base class column processing or 3D processing.
   subroutine process_run(this, state_manager, dt, error_manager)
      class(ProcessDustInterface), intent(inout) :: this
      type(StateManagerType), intent(inout) :: state_manager
      real(fp), intent(in) :: dt
      type(ErrorManagerType), intent(inout) :: error_manager

      ! Use standard 3D processing
      call this%run_3d_processing(state_manager, dt, error_manager)

   end subroutine process_run

   !> Finalize the dust process
   subroutine process_finalize(this, error_manager)
      class(ProcessDustInterface), intent(inout) :: this
      type(ErrorManagerType), intent(inout) :: error_manager

      ! Call base class finalization (handles common cleanup)
      call this%ProcessInterface%finalize(error_manager)

   end subroutine process_finalize

   !> Configure all schemes for this process
   subroutine configure_schemes(this, config_data, error_manager)
      class(ProcessDustInterface), intent(inout) :: this
      type(ConfigDataType), intent(in) :: config_data
      type(ErrorManagerType), intent(inout) :: error_manager

      ! Parse active scheme from configuration
      call config_data%get_value('active_scheme', this%active_scheme, error_manager)
      if (error_manager%has_error()) return

      ! Configure scheme-specific parameters
      select case (trim(this%active_scheme))
      case ('fengsha')
         call config_data%get_section('fengsha', this%config_fengsha, error_manager)
      case ('ginoux')
         call config_data%get_section('ginoux', this%config_ginoux, error_manager)
      case default
         call error_manager%set_error(CC_FAILURE, &
            "Unknown dust scheme: " // trim(this%active_scheme))
      end select

   end subroutine configure_schemes


   !> Run the active scheme (delegation pattern)
   subroutine run_active_scheme(this, state_manager, i_col, dt, error_manager)
      class(ProcessDustInterface), intent(inout) :: this
      type(StateManagerType), intent(inout) :: state_manager
      integer, intent(in) :: i_col
      real(fp), intent(in) :: dt
      type(ErrorManagerType), intent(inout) :: error_manager

      ! Delegate to appropriate scheme
      select case (trim(this%active_scheme))
      case ('fengsha')
         call this%run_fengsha_scheme(state_manager, i_col, dt, error_manager)
      case ('ginoux')
         call this%run_ginoux_scheme(state_manager, i_col, dt, error_manager)
      case default
         call error_manager%set_error(CC_FAILURE, &
            "Unknown dust scheme: " // trim(this%active_scheme))
      end select

   end subroutine run_active_scheme

   !> Run the fengsha scheme (simplified data marshaling)
   subroutine run_fengsha_scheme(this, state_manager, i_col, dt, error_manager)
      class(ProcessDustInterface), intent(inout) :: this
      type(StateManagerType), intent(inout) :: state_manager
      integer, intent(in) :: i_col
      real(fp), intent(in) :: dt
      type(ErrorManagerType), intent(inout) :: error_manager

      ! Local variables for scheme calculation (simplified)
      ! Meteorological fields - use utility helper for retrieval
      real(fp) :: is_land
      real(fp) :: friction_velocity
      real(fp) :: land_water_index
      real(fp) :: green_veg_fraction
      real(fp) :: leaf_area_index
      real(fp) :: ocean_fraction
      real(fp) :: clay_fraction
      real(fp) :: sand_fraction
      real(fp) :: snow_fraction
      real(fp) :: drag_partition
      real(fp) :: soil_moisture
      real(fp) :: threshold_ustar

      ! Species data - use species utilities
      real(fp), allocatable :: species_conc(:)
      real(fp), allocatable :: species_tendencies(:)
      integer :: n_species, n_levels
      integer, allocatable :: species_indices(:)

      ! Get dimensions from state manager
      n_levels = state_manager%get_n_levels()
      call this%species_utils%get_indices([], species_indices, error_manager)
      if (error_manager%has_error()) return
      n_species = size(species_indices)

      ! Allocate arrays
      allocate(species_conc(n_species))
      allocate(species_tendencies(n_species))
      species_tendencies = 0.0_fp

      ! Retrieve meteorological fields using utilities
      call this%met_utils%get_field('IsLand', state_manager, i_col, is_land, error_manager)
      if (error_manager%has_error()) return
      call this%met_utils%get_field('USTAR', state_manager, i_col, friction_velocity, error_manager)
      if (error_manager%has_error()) return
      call this%met_utils%get_field('LWI', state_manager, i_col, land_water_index, error_manager)
      if (error_manager%has_error()) return
      call this%met_utils%get_field('GVF', state_manager, i_col, green_veg_fraction, error_manager)
      if (error_manager%has_error()) return
      call this%met_utils%get_field('LAI', state_manager, i_col, leaf_area_index, error_manager)
      if (error_manager%has_error()) return
      call this%met_utils%get_field('FROCEAN', state_manager, i_col, ocean_fraction, error_manager)
      if (error_manager%has_error()) return
      call this%met_utils%get_field('CLAYFRAC', state_manager, i_col, clay_fraction, error_manager)
      if (error_manager%has_error()) return
      call this%met_utils%get_field('SANDFRAC', state_manager, i_col, sand_fraction, error_manager)
      if (error_manager%has_error()) return
      call this%met_utils%get_field('FRSNO', state_manager, i_col, snow_fraction, error_manager)
      if (error_manager%has_error()) return
      call this%met_utils%get_field('RDRAG', state_manager, i_col, drag_partition, error_manager)
      if (error_manager%has_error()) return
      call this%met_utils%get_field('SSM', state_manager, i_col, soil_moisture, error_manager)
      if (error_manager%has_error()) return
      call this%met_utils%get_field('USTAR_THRESHOLD', state_manager, i_col, threshold_ustar, error_manager)
      if (error_manager%has_error()) return

      ! Get species concentrations using utilities
      call this%species_utils%get_concentrations(species_indices, state_manager, i_col, species_conc, error_manager)
      if (error_manager%has_error()) return

      ! Call the science scheme (clean interface)
      call compute_fengsha( &
         n_levels, &
         n_species, &
         this%config_fengsha, &
         is_land, &         friction_velocity, &         land_water_index, &         green_veg_fraction, &         leaf_area_index, &         ocean_fraction, &         clay_fraction, &         sand_fraction, &         snow_fraction, &         drag_partition, &         soil_moisture, &         threshold_ustar, &
         species_conc, &
         species_tendencies &
      )

      ! Apply tendencies using base class utilities
      call this%apply_tendency(species_indices, state_manager, i_col, species_tendencies, dt, error_manager)
      if (error_manager%has_error()) return

      ! Update process diagnostics (handled by base class)
      call this%update_process_diagnostics(species_tendencies, state_manager, i_col, error_manager)

   end subroutine run_fengsha_scheme

   !> Run the ginoux scheme (simplified data marshaling)
   subroutine run_ginoux_scheme(this, state_manager, i_col, dt, error_manager)
      class(ProcessDustInterface), intent(inout) :: this
      type(StateManagerType), intent(inout) :: state_manager
      integer, intent(in) :: i_col
      real(fp), intent(in) :: dt
      type(ErrorManagerType), intent(inout) :: error_manager

      ! Local variables for scheme calculation (simplified)
      ! Meteorological fields - use utility helper for retrieval
      real(fp) :: lake_fraction
      real(fp) :: top_soil_wetness
      real(fp) :: u_wind_10m
      real(fp) :: v_wind_10m
      real(fp) :: soil_moisture

      ! Species data - use species utilities
      real(fp), allocatable :: species_conc(:)
      real(fp), allocatable :: species_tendencies(:)
      integer :: n_species, n_levels
      integer, allocatable :: species_indices(:)

      ! Get dimensions from state manager
      n_levels = state_manager%get_n_levels()
      call this%species_utils%get_indices([], species_indices, error_manager)
      if (error_manager%has_error()) return
      n_species = size(species_indices)

      ! Allocate arrays
      allocate(species_conc(n_species))
      allocate(species_tendencies(n_species))
      species_tendencies = 0.0_fp

      ! Retrieve meteorological fields using utilities
      call this%met_utils%get_field('FRLAKE', state_manager, i_col, lake_fraction, error_manager)
      if (error_manager%has_error()) return
      call this%met_utils%get_field('GWETTOP', state_manager, i_col, top_soil_wetness, error_manager)
      if (error_manager%has_error()) return
      call this%met_utils%get_field('U10M', state_manager, i_col, u_wind_10m, error_manager)
      if (error_manager%has_error()) return
      call this%met_utils%get_field('V10M', state_manager, i_col, v_wind_10m, error_manager)
      if (error_manager%has_error()) return
      call this%met_utils%get_field('SSM', state_manager, i_col, soil_moisture, error_manager)
      if (error_manager%has_error()) return

      ! Get species concentrations using utilities
      call this%species_utils%get_concentrations(species_indices, state_manager, i_col, species_conc, error_manager)
      if (error_manager%has_error()) return

      ! Call the science scheme (clean interface)
      call compute_ginoux( &
         n_levels, &
         n_species, &
         this%config_ginoux, &
         lake_fraction, &         top_soil_wetness, &         u_wind_10m, &         v_wind_10m, &         soil_moisture, &
         species_conc, &
         species_tendencies &
      )

      ! Apply tendencies using base class utilities
      call this%apply_tendency(species_indices, state_manager, i_col, species_tendencies, dt, error_manager)
      if (error_manager%has_error()) return

      ! Update process diagnostics (handled by base class)
      call this%update_process_diagnostics(species_tendencies, state_manager, i_col, error_manager)

   end subroutine run_ginoux_scheme


   !> Get required meteorological fields for this process
   function get_required_met_fields(this) result(field_names)
      class(ProcessDustInterface), intent(in) :: this
      character(len=64), allocatable :: field_names(:)

      ! Combine common fields with scheme-specific fields
      integer :: n_common, n_scheme, n_total
      character(len=64), allocatable :: common_fields(:), scheme_fields(:)

      ! Common fields for all schemes
      n_common = 3
      allocate(common_fields(n_common))
      common_fields(1) = 'ustar'
      common_fields(2) = 'solar_zenith_angle'
      common_fields(3) = 'leaf_area_index'

      ! Scheme-specific fields
      select case (trim(this%active_scheme))
      case ('fengsha')
         n_scheme = 12
         allocate(scheme_fields(n_scheme))
         scheme_fields(1) = 'IsLand'
         scheme_fields(2) = 'USTAR'
         scheme_fields(3) = 'LWI'
         scheme_fields(4) = 'GVF'
         scheme_fields(5) = 'LAI'
         scheme_fields(6) = 'FROCEAN'
         scheme_fields(7) = 'CLAYFRAC'
         scheme_fields(8) = 'SANDFRAC'
         scheme_fields(9) = 'FRSNO'
         scheme_fields(10) = 'RDRAG'
         scheme_fields(11) = 'SSM'
         scheme_fields(12) = 'USTAR_THRESHOLD'
      case ('ginoux')
         n_scheme = 5
         allocate(scheme_fields(n_scheme))
         scheme_fields(1) = 'FRLAKE'
         scheme_fields(2) = 'GWETTOP'
         scheme_fields(3) = 'U10M'
         scheme_fields(4) = 'V10M'
         scheme_fields(5) = 'SSM'
      case default
         n_scheme = 0
         allocate(scheme_fields(0))
      end select

      ! Combine fields
      n_total = n_common + n_scheme
      allocate(field_names(n_total))
      if (n_common > 0) field_names(1:n_common) = common_fields
      if (n_scheme > 0) field_names(n_common+1:n_total) = scheme_fields

   end function get_required_met_fields

   !> Get required diagnostic fields for this process
   function get_required_diagnostic_fields(this) result(field_names)
      class(ProcessDustInterface), intent(in) :: this
      character(len=64), allocatable :: field_names(:)

      allocate(field_names(1))
      field_names(1) = 'total_dust_emission'

   end function get_required_diagnostic_fields

end module ProcessDustInterface_Mod