!> Process for computing sea salt aerosol emissions over ocean surfaces
!!
!! This module provides the seasalt process interface for the CATChem library.
!! The interface leverages CATChem's core infrastructure for data marshaling and process management.
!! All algorithmic calculations are performed in separate scheme modules.
!!
!! This code was generated by the CATChem Process Generator.
!! Generation date: 2025-08-11T15:55:19.425161
!! Configuration: seasalt
!!
!! @author CATChem Process Generator
!! @version 1.0.0

module ProcessSeaSaltInterface_Mod

   ! Core CATChem infrastructure
   use precision_mod, only: fp
   use ProcessInterface_Mod, only: ProcessInterface, ColumnProcessInterface
   use StateManager_Mod, only: StateManagerType
   use GridManager_Mod, only: GridManagerType
   use error_mod, only: CC_SUCCESS, CC_FAILURE, ErrorManagerType
   use DiagnosticManager_Mod, only: DiagnosticManagerType
   use VirtualColumn_Mod, only: VirtualColumnType

   ! Core utilities (leverage existing infrastructure)
   use UnitConversion_Mod, only: UnitConverterType
   use ConfigManager_Mod, only: ConfigDataType
   use ChemState_Mod, only: ChemStateType
   use MetState_Mod, only: MetStateType

   ! Common utilities - unified configuration
   use SeaSaltCommon_Mod, only: SeaSaltProcessConfig

   ! Scheme modules
   use gong97_scheme_mod, only: compute_gong97
   use gong03_scheme_mod, only: compute_gong03
   use geos12_scheme_mod, only: compute_geos12

   implicit none
   private

   public :: ProcessSeaSaltInterface

   !> Main seasalt process interface type - extends core ColumnProcessInterface   !!
   !! This type leverages CATChem's core ColumnProcessInterface infrastructure for column
   !! virtualization, focusing only on process-specific configuration and scheme management.
   !! All boilerplate infrastructure and column processing is handled by the base class.
   type, extends(ColumnProcessInterface) :: ProcessSeaSaltInterface
      private

      ! Unified process configuration (bridges ConfigManager to process-specific config)
      type(SeaSaltProcessConfig) :: process_config

      ! Process utilities (leverage core infrastructure)
      type(UnitConverterType) :: unit_converter
      type(ChemStateType), pointer :: chem_state => null()
      type(MetStateType), pointer :: met_state => null()

      ! Process-specific diagnostic indices (base class handles storage)
      integer :: diag_seasalt_mass_emission_total_idx = -1
      integer :: diag_seasalt_number_emission_total_idx = -1

   contains
      ! Required ProcessInterface implementations
      procedure :: init => process_init
      procedure :: run => process_run
      procedure :: finalize => process_finalize
      procedure :: parse_process_config => parse_seasalt_config

      ! Required ColumnProcessInterface implementations
      procedure :: init_column_processing => init_column_processing
      procedure :: run_column => run_column
      procedure :: finalize_column_processing => finalize_column_processing

      ! ProcessInterface capability registration
      procedure :: get_required_met_fields => get_required_met_fields
      procedure :: get_required_diagnostic_fields => get_required_diagnostic_fields

      ! Process-specific implementations (column virtualization)      procedure, private :: run_active_scheme_column
      procedure, private :: run_gong97_scheme_column
      procedure, private :: run_gong03_scheme_column
      procedure, private :: run_geos12_scheme_column

   end type ProcessSeaSaltInterface

contains

   !> Initialize the seasalt process
   !!
   !! Leverages ProcessInterface base class for common initialization tasks.
   !! Only handles process-specific configuration and scheme setup.
   subroutine process_init(this, state_manager, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      type(StateManagerType), intent(inout) :: state_manager
      integer, intent(out) :: rc

      type(ErrorManagerType), pointer :: error_manager

      rc = CC_SUCCESS

      ! Get error manager
      error_manager => state_manager%get_error_manager()

      ! Call base class initialization (handles common infrastructure)
      call this%ColumnProcessInterface%init(state_manager, rc)
      if (rc /= CC_SUCCESS) return

      ! Initialize column processing capabilities
      call this%init_column_processing(state_manager, rc)
      if (rc /= CC_SUCCESS) return

      ! Set process-specific name and info
      call this%set_name('seasalt')
      call this%set_version('1.0.0')
      call this%set_description('Process for computing sea salt aerosol emissions over ocean surfaces')

      ! Parse process-specific configuration using unified approach
      call this%parse_process_config(state_manager, error_manager)
      if (error_manager%has_error()) then
         rc = CC_FAILURE
         return
      end if

      ! Get state pointers from state_manager (needed for species loading)
      this%chem_state => state_manager%get_chem_state_ptr()
      this%met_state => state_manager%get_met_state_ptr()

      ! Load species from ChemState based on is_seasalt property
      call this%process_config%load_species_from_chem_state(this%chem_state, error_manager)
      if (error_manager%has_error()) then
         rc = CC_FAILURE
         return
      end if

      ! Validate the configuration with StateManager
      call this%process_config%validate(state_manager, error_manager)
      if (error_manager%has_error()) then
         rc = CC_FAILURE
         return
      end if

      ! Initialize utility helpers
      call this%unit_converter%init(error_manager)
      if (error_manager%has_error()) then
         rc = CC_FAILURE
         return
      end if

   end subroutine process_init

   !> Run the seasalt process
   !!
   !! This method implements the main ProcessInterface run method.
   !! For ColumnProcessInterface processes, the actual column iteration is handled
   !! by ProcessManager, so this method serves as a placeholder for any 3D operations
   !! that might be needed before or after column processing.
   subroutine process_run(this, state_manager, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      type(StateManagerType), intent(inout) :: state_manager
      integer, intent(out) :: rc

      rc = CC_SUCCESS

      ! Check if process is active
      if (.not. this%process_config%is_active) then
         return
      end if

      ! For ColumnProcessInterface processes, the ProcessManager handles column iteration
      ! and calls run_column() for each virtual column. This method is mainly a placeholder
      ! for any global 3D operations that need to happen before/after column processing.
      
      ! Currently no global 3D operations needed for seasalt process
      ! All processing happens in run_column() method

   end subroutine process_run

   !> Finalize the seasalt process
   subroutine process_finalize(this, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      integer, intent(out) :: rc

      rc = CC_SUCCESS

      ! Finalize column processing
      call this%finalize_column_processing(rc)
      if (rc /= CC_SUCCESS) return

      ! Finalize unified configuration
      call this%process_config%finalize()

      ! Call base class finalization (handles common cleanup)
      call this%ColumnProcessInterface%finalize(rc)

   end subroutine process_finalize

   !> Parse process configuration using unified approach
   !! This function bridges the ConfigManager YAML structure to process-specific configuration
   subroutine parse_seasalt_config(this, state_manager, error_manager)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      type(StateManagerType), intent(in) :: state_manager
      type(ErrorManagerType), intent(inout) :: error_manager

      type(ConfigDataType), pointer :: config_data

      ! Get configuration data from state manager
      config_data => state_manager%get_config_data()

      ! Use the unified configuration loader from SeaSaltCommon_Mod
      ! This handles the complexity of parsing hierarchical YAML into process-specific types
      call this%process_config%load_from_config(config_data, error_manager)
      if (error_manager%has_error()) then
         call error_manager%add_context("ProcessSeaSaltInterface", &
            "Failed to parse seasalt process configuration")
         return
      end if

      ! Process is now configured - the unified config contains all scheme-specific settings

   end subroutine parse_seasalt_config

   !========================================================================
   ! Column Processing Interface Implementation
   !========================================================================

   !> Initialize column processing for seasalt
   !!
   !! This method sets up the column processing infrastructure for the process.
   !! The base class ColumnProcessInterface handles the actual column virtualization.
   subroutine init_column_processing(this, state_manager, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      type(StateManagerType), intent(inout) :: state_manager
      integer, intent(out) :: rc

      rc = CC_SUCCESS

      ! Enable column processing and set batch size for optimal performance
      call this%enable_column_processing()
      call this%set_column_batch_size(50)  ! Process 50 columns at a time

      ! Any process-specific column processing setup would go here
      ! For seasalt, no additional setup is needed

   end subroutine init_column_processing

   !> Process a single virtual column for seasalt
   !!
   !! This is the core column processing method where the actual atmospheric process
   !! calculations happen for a single column. The base class handles column
   !! virtualization and calls this method for each virtual column.
   subroutine run_column(this, column, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      type(VirtualColumnType), intent(inout) :: column
      integer, intent(out) :: rc

      rc = CC_SUCCESS

      ! Check if process is active
      if (.not. this%process_config%is_active) return

      ! Delegate to the active scheme for column processing
      call this%run_active_scheme_column(column, rc)

   end subroutine run_column

   !> Finalize column processing for seasalt
   !!
   !! Clean up any column processing resources.
   subroutine finalize_column_processing(this, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      integer, intent(out) :: rc

      rc = CC_SUCCESS

      ! Clean up column processing
      call this%disable_column_processing()

      ! Any process-specific cleanup would go here

   end subroutine finalize_column_processing

   !> Run the active scheme for a single virtual column
   !!
   !! This method adapts the existing scheme methods to work with virtual columns
   !! instead of state manager column indices.
   subroutine run_active_scheme_column(this, column, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      type(VirtualColumnType), intent(inout) :: column
      integer, intent(out) :: rc

      rc = CC_SUCCESS

      ! Delegate to appropriate scheme using unified config
      select case (trim(this%process_config%seasalt_config%scheme))
      case ('gong97')
         call this%run_gong97_scheme_column(column, rc)
      case ('gong03')
         call this%run_gong03_scheme_column(column, rc)
      case ('geos12')
         call this%run_geos12_scheme_column(column, rc)
      case default
         rc = CC_FAILURE
      end select

   end subroutine run_active_scheme_column

   !> Run the gong97 scheme for a single virtual column
   subroutine run_gong97_scheme_column(this, column, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      type(VirtualColumnType), intent(inout) :: column
      integer, intent(out) :: rc

      ! Local variables for scheme calculation
      ! Meteorological fields
      real(fp), allocatable :: frocean(:)
      real(fp), allocatable :: frseaice(:)
      real(fp), allocatable :: sst(:)
      real(fp), allocatable :: u10m(:)
      real(fp), allocatable :: v10m(:)
      ! Species properties
      real(fp), allocatable :: species_density(:)
      real(fp), allocatable :: species_radius(:)
      real(fp), allocatable :: species_lower_radius(:)
      real(fp), allocatable :: species_upper_radius(:)
      real(fp), allocatable :: species_conc(:)
      real(fp), allocatable :: species_tendencies(:)
      integer :: n_species, n_levels
      integer, allocatable :: species_indices(:)

      rc = CC_SUCCESS

      ! Get dimensions from virtual column
      n_levels = column%get_n_levels()
      
      ! Get seasalt species information from process configuration
      n_species = this%process_config%seasalt_config%n_species
      if (n_species <= 0) then
         return
      end if
      
      ! Get species indices directly from configuration (pre-computed)
      allocate(species_indices(n_species))
      species_indices(1:n_species) = this%process_config%seasalt_config%species_indices(1:n_species)

      ! Allocate arrays
      allocate(species_conc(n_species))
      allocate(species_tendencies(n_species))
      allocate(frocean(1), frseaice(1), sst(1), u10m(1), v10m(1))
      allocate(species_density(n_species), species_radius(n_species), species_lower_radius(n_species), species_upper_radius(n_species))
      species_tendencies = 0.0_fp

      ! Get meteorological fields from virtual column
      call column%get_met_field('FROCEAN', frocean, rc)
      if (rc /= CC_SUCCESS) return
      call column%get_met_field('FRSEAICE', frseaice, rc)
      if (rc /= CC_SUCCESS) return
      call column%get_met_field('SST', sst, rc)
      if (rc /= CC_SUCCESS) return
      call column%get_met_field('U10M', u10m, rc)
      if (rc /= CC_SUCCESS) return
      call column%get_met_field('V10M', v10m, rc)
      if (rc /= CC_SUCCESS) return

      ! Get species concentrations from virtual column
      call column%get_species_concentrations(species_indices, species_conc, rc)
      if (rc /= CC_SUCCESS) return

      ! Get species properties from configuration (pre-loaded during initialization)
      ! Use species properties from process configuration
      species_density(1:n_species) = this%process_config%seasalt_config%species_density(1:n_species)
      ! Use species properties from process configuration
      species_radius(1:n_species) = this%process_config%seasalt_config%species_radius(1:n_species)
      ! Use species properties from process configuration
      species_lower_radius(1:n_species) = this%process_config%seasalt_config%species_lower_radius(1:n_species)
      ! Use species properties from process configuration
      species_upper_radius(1:n_species) = this%process_config%seasalt_config%species_upper_radius(1:n_species)

      ! Call the science scheme
      call compute_gong97( &
         n_levels, &
         n_species, &
         this%process_config%gong97_config, &
         frocean, &
         frseaice, &
         sst, &
         u10m, &
         v10m, &
         species_density, &
         species_radius, &
         species_lower_radius, &
         species_upper_radius, &
         species_conc, &
         species_tendencies &
      )

      ! Apply tendencies back to virtual column
      call column%apply_species_tendencies(species_indices, species_tendencies, this%get_timestep(), rc)

   end subroutine run_gong97_scheme_column

   !> Run the gong03 scheme for a single virtual column
   subroutine run_gong03_scheme_column(this, column, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      type(VirtualColumnType), intent(inout) :: column
      integer, intent(out) :: rc

      ! Local variables for scheme calculation
      ! Meteorological fields
      real(fp), allocatable :: frocean(:)
      real(fp), allocatable :: frseaice(:)
      real(fp), allocatable :: sst(:)
      real(fp), allocatable :: u10m(:)
      real(fp), allocatable :: v10m(:)
      ! Species properties
      real(fp), allocatable :: species_density(:)
      real(fp), allocatable :: species_radius(:)
      real(fp), allocatable :: species_lower_radius(:)
      real(fp), allocatable :: species_upper_radius(:)
      real(fp), allocatable :: species_conc(:)
      real(fp), allocatable :: species_tendencies(:)
      integer :: n_species, n_levels
      integer, allocatable :: species_indices(:)

      rc = CC_SUCCESS

      ! Get dimensions from virtual column
      n_levels = column%get_n_levels()
      
      ! Get seasalt species information from process configuration
      n_species = this%process_config%seasalt_config%n_species
      if (n_species <= 0) then
         return
      end if
      
      ! Get species indices directly from configuration (pre-computed)
      allocate(species_indices(n_species))
      species_indices(1:n_species) = this%process_config%seasalt_config%species_indices(1:n_species)

      ! Allocate arrays
      allocate(species_conc(n_species))
      allocate(species_tendencies(n_species))
      allocate(frocean(1), frseaice(1), sst(1), u10m(1), v10m(1))
      allocate(species_density(n_species), species_radius(n_species), species_lower_radius(n_species), species_upper_radius(n_species))
      species_tendencies = 0.0_fp

      ! Get meteorological fields from virtual column
      call column%get_met_field('FROCEAN', frocean, rc)
      if (rc /= CC_SUCCESS) return
      call column%get_met_field('FRSEAICE', frseaice, rc)
      if (rc /= CC_SUCCESS) return
      call column%get_met_field('SST', sst, rc)
      if (rc /= CC_SUCCESS) return
      call column%get_met_field('U10M', u10m, rc)
      if (rc /= CC_SUCCESS) return
      call column%get_met_field('V10M', v10m, rc)
      if (rc /= CC_SUCCESS) return

      ! Get species concentrations from virtual column
      call column%get_species_concentrations(species_indices, species_conc, rc)
      if (rc /= CC_SUCCESS) return

      ! Get species properties from configuration (pre-loaded during initialization)
      ! Use species properties from process configuration
      species_density(1:n_species) = this%process_config%seasalt_config%species_density(1:n_species)
      ! Use species properties from process configuration
      species_radius(1:n_species) = this%process_config%seasalt_config%species_radius(1:n_species)
      ! Use species properties from process configuration
      species_lower_radius(1:n_species) = this%process_config%seasalt_config%species_lower_radius(1:n_species)
      ! Use species properties from process configuration
      species_upper_radius(1:n_species) = this%process_config%seasalt_config%species_upper_radius(1:n_species)

      ! Call the science scheme
      call compute_gong03( &
         n_levels, &
         n_species, &
         this%process_config%gong03_config, &
         frocean, &
         frseaice, &
         sst, &
         u10m, &
         v10m, &
         species_density, &
         species_radius, &
         species_lower_radius, &
         species_upper_radius, &
         species_conc, &
         species_tendencies &
      )

      ! Apply tendencies back to virtual column
      call column%apply_species_tendencies(species_indices, species_tendencies, this%get_timestep(), rc)

   end subroutine run_gong03_scheme_column

   !> Run the geos12 scheme for a single virtual column
   subroutine run_geos12_scheme_column(this, column, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      type(VirtualColumnType), intent(inout) :: column
      integer, intent(out) :: rc

      ! Local variables for scheme calculation
      ! Meteorological fields
      real(fp), allocatable :: frocean(:)
      real(fp), allocatable :: frseaice(:)
      real(fp), allocatable :: sst(:)
      real(fp), allocatable :: ustar(:)
      ! Species properties
      real(fp), allocatable :: species_density(:)
      real(fp), allocatable :: species_radius(:)
      real(fp), allocatable :: species_lower_radius(:)
      real(fp), allocatable :: species_upper_radius(:)
      real(fp), allocatable :: species_conc(:)
      real(fp), allocatable :: species_tendencies(:)
      integer :: n_species, n_levels
      integer, allocatable :: species_indices(:)

      rc = CC_SUCCESS

      ! Get dimensions from virtual column
      n_levels = column%get_n_levels()
      
      ! Get seasalt species information from process configuration
      n_species = this%process_config%seasalt_config%n_species
      if (n_species <= 0) then
         return
      end if
      
      ! Get species indices directly from configuration (pre-computed)
      allocate(species_indices(n_species))
      species_indices(1:n_species) = this%process_config%seasalt_config%species_indices(1:n_species)

      ! Allocate arrays
      allocate(species_conc(n_species))
      allocate(species_tendencies(n_species))
      allocate(frocean(1), frseaice(1), sst(1), ustar(1))
      allocate(species_density(n_species), species_radius(n_species), species_lower_radius(n_species), species_upper_radius(n_species))
      species_tendencies = 0.0_fp

      ! Get meteorological fields from virtual column
      call column%get_met_field('FROCEAN', frocean, rc)
      if (rc /= CC_SUCCESS) return
      call column%get_met_field('FRSEAICE', frseaice, rc)
      if (rc /= CC_SUCCESS) return
      call column%get_met_field('SST', sst, rc)
      if (rc /= CC_SUCCESS) return
      call column%get_met_field('USTAR', ustar, rc)
      if (rc /= CC_SUCCESS) return

      ! Get species concentrations from virtual column
      call column%get_species_concentrations(species_indices, species_conc, rc)
      if (rc /= CC_SUCCESS) return

      ! Get species properties from configuration (pre-loaded during initialization)
      ! Use species properties from process configuration
      species_density(1:n_species) = this%process_config%seasalt_config%species_density(1:n_species)
      ! Use species properties from process configuration
      species_radius(1:n_species) = this%process_config%seasalt_config%species_radius(1:n_species)
      ! Use species properties from process configuration
      species_lower_radius(1:n_species) = this%process_config%seasalt_config%species_lower_radius(1:n_species)
      ! Use species properties from process configuration
      species_upper_radius(1:n_species) = this%process_config%seasalt_config%species_upper_radius(1:n_species)

      ! Call the science scheme
      call compute_geos12( &
         n_levels, &
         n_species, &
         this%process_config%geos12_config, &
         frocean, &
         frseaice, &
         sst, &
         ustar, &
         species_density, &
         species_radius, &
         species_lower_radius, &
         species_upper_radius, &
         species_conc, &
         species_tendencies &
      )

      ! Apply tendencies back to virtual column
      call column%apply_species_tendencies(species_indices, species_tendencies, this%get_timestep(), rc)

   end subroutine run_geos12_scheme_column


   !> Get required meteorological fields for this process
   function get_required_met_fields(this) result(field_names)
      class(ProcessSeaSaltInterface), intent(in) :: this
      character(len=64), allocatable :: field_names(:)

      ! Combine common fields with scheme-specific fields
      integer :: n_common, n_scheme, n_total
      character(len=64), allocatable :: common_fields(:), scheme_fields(:)

      ! Common fields for all schemes
      n_common = 3
      allocate(common_fields(n_common))
      common_fields(1) = 'FROCEAN'
      common_fields(2) = 'FRSEAICE'
      common_fields(3) = 'SST'

      ! Scheme-specific fields
      select case (trim(this%process_config%seasalt_config%scheme))
      case ('gong97')
         n_scheme = 5
         allocate(scheme_fields(n_scheme))
         scheme_fields(1) = 'FROCEAN'
         scheme_fields(2) = 'FRSEAICE'
         scheme_fields(3) = 'SST'
         scheme_fields(4) = 'U10M'
         scheme_fields(5) = 'V10M'
      case ('gong03')
         n_scheme = 5
         allocate(scheme_fields(n_scheme))
         scheme_fields(1) = 'FROCEAN'
         scheme_fields(2) = 'FRSEAICE'
         scheme_fields(3) = 'SST'
         scheme_fields(4) = 'U10M'
         scheme_fields(5) = 'V10M'
      case ('geos12')
         n_scheme = 4
         allocate(scheme_fields(n_scheme))
         scheme_fields(1) = 'FROCEAN'
         scheme_fields(2) = 'FRSEAICE'
         scheme_fields(3) = 'SST'
         scheme_fields(4) = 'USTAR'
      case default
         n_scheme = 0
         allocate(scheme_fields(0))
      end select

      ! Combine fields
      n_total = n_common + n_scheme
      allocate(field_names(n_total))
      if (n_common > 0) field_names(1:n_common) = common_fields
      if (n_scheme > 0) field_names(n_common+1:n_total) = scheme_fields

   end function get_required_met_fields

   !> Get required diagnostic fields for this process
   function get_required_diagnostic_fields(this) result(field_names)
      class(ProcessSeaSaltInterface), intent(in) :: this
      character(len=64), allocatable :: field_names(:)

      allocate(field_names(2))
      field_names(1) = 'seasalt_mass_emission_total'
      field_names(2) = 'seasalt_number_emission_total'

   end function get_required_diagnostic_fields

end module ProcessSeaSaltInterface_Mod