!> Process for computing sea salt aerosol emissions over ocean surfaces
!!
!! This module provides the seasalt process interface for the CATChem library.
!! The interface leverages CATChem's core infrastructure for data marshaling and process management.
!! All algorithmic calculations are performed in separate scheme modules.
!!
!! DIAGNOSTIC INTERFACE:
!! The compute_scheme functions support optional diagnostic parameters. When diagnostics are
!! enabled in the configuration, these parameters are passed to capture emission/tendency data.
!! When diagnostics are disabled, the scheme calls use the original interface without diagnostics.
!! This approach maintains backward compatibility while providing flexible diagnostic capabilities.
!!
!! This code was generated by the CATChem Process Generator.
!! Generation date: 2025-08-28T14:16:31.618515
!! Configuration: seasalt
!!
!! @author CATChem Process Generator
!! @version 1.0.0

module ProcessSeaSaltInterface_Mod

   ! Core CATChem infrastructure
   use precision_mod, only: fp
   use ProcessInterface_Mod, only: ProcessInterface, ColumnProcessInterface
   use StateManager_Mod, only: StateManagerType
   use GridManager_Mod, only: GridManagerType
   use error_mod, only: CC_SUCCESS, CC_FAILURE, CC_Error, CC_Warning
   use DiagnosticManager_Mod, only: DiagnosticManagerType
   use DiagnosticInterface_Mod, only: DiagnosticRegistryType, DiagnosticFieldType, DiagnosticDataType
   use VirtualColumn_Mod, only: VirtualColumnType, VirtualMetType

   ! Core utilities (leverage existing infrastructure)
   use UnitConversion_Mod, only: UnitConverterType
   use ConfigManager_Mod, only: ConfigManagerType
   use ChemState_Mod, only: ChemStateType
   use MetState_Mod, only: MetStateType

   ! Common utilities - unified configuration
   use SeaSaltCommon_Mod, only: SeaSaltProcessConfig

   ! Scheme modules
   use gong97_scheme_mod, only: compute_gong97
   use gong03_scheme_mod, only: compute_gong03
   use geos12_scheme_mod, only: compute_geos12

   implicit none
   private

   public :: ProcessSeaSaltInterface

   !> Main seasalt process interface type - extends core ColumnProcessInterface   !!
   !! This type leverages CATChem's core ColumnProcessInterface infrastructure for column
   !! virtualization, focusing only on process-specific configuration and scheme management.
   !! All boilerplate infrastructure and column processing is handled by the base class.
   type, extends(ColumnProcessInterface) :: ProcessSeaSaltInterface
      private

      ! Unified process configuration (bridges ConfigManager to process-specific config)
      type(SeaSaltProcessConfig) :: process_config

      ! Process utilities (leverage core infrastructure)
      type(UnitConverterType) :: unit_converter
      type(ChemStateType), pointer :: chem_state => null()
      type(MetStateType), pointer :: met_state => null()
      type(StateManagerType), pointer :: state_manager => null()

      ! Process-specific diagnostic indices (base class handles storage)
      integer :: diag_seasalt_mass_emission_total_idx = -1
      integer :: diag_seasalt_number_emission_total_idx = -1

      ! Column-level diagnostic storage for interfacing with DiagManager
      ! These are allocated per-column during processing and can be used to
      ! accumulate data for DiagManager updates
      real(fp), allocatable :: column_seasalt_mass_emission_total              ! scalar - per column
      real(fp), allocatable :: column_seasalt_number_emission_total              ! scalar - per column

      ! Scheme-specific diagnostic storage (shared across all schemes that use them)
      real(fp), allocatable :: column_seasalt_mass_emission_per_bin(:)           ! scheme-specific 1D: species - per column
      real(fp), allocatable :: column_seasalt_number_emission_per_bin(:)           ! scheme-specific 1D: species - per column

   contains
      ! Required ProcessInterface implementations
      procedure :: init => process_init
      procedure :: run => process_run
      procedure :: finalize => process_finalize
      procedure :: parse_process_config => parse_seasalt_config

      ! Required ColumnProcessInterface implementations
      procedure :: init_column_processing => init_column_processing
      procedure :: run_column => run_column
      procedure :: finalize_column_processing => finalize_column_processing
      procedure :: get_state_manager => get_state_manager_impl

      ! ProcessInterface capability registration
      procedure :: get_required_met_fields => get_required_met_fields
      procedure :: get_required_diagnostic_fields => get_required_diagnostic_fields

      ! Process-specific implementations (column virtualization)      procedure, private :: run_active_scheme_column
      procedure, private :: run_gong97_scheme_column
      procedure, private :: run_gong03_scheme_column
      procedure, private :: run_geos12_scheme_column

      ! Diagnostic procedures (override base class method)
      procedure :: register_diagnostics => register_process_diagnostics
      procedure, private :: register_process_diagnostics
      procedure, private :: calculate_and_update_diagnostics

   end type ProcessSeaSaltInterface

contains

   !> Initialize the seasalt process
   !!
   !! Leverages ProcessInterface base class for common initialization tasks.
   !! Only handles process-specific configuration and scheme setup.
   subroutine process_init(this, state_manager, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      type(StateManagerType), intent(inout) :: state_manager
      integer, intent(out) :: rc

      type(ErrorManagerType), pointer :: error_manager
      type(GridManagerType), pointer :: grid_mgr

      rc = CC_SUCCESS

      ! Get error manager
      error_manager => state_manager%get_error_manager()

      ! Get grid manager for diagnostic allocation
      grid_mgr => state_manager%get_grid_manager()

      ! Call base class initialization (handles common infrastructure)
      call this%ColumnProcessInterface%init(state_manager, rc)
      if (rc /= CC_SUCCESS) return

      ! Initialize column processing capabilities
      call this%init_column_processing(state_manager, rc)
      if (rc /= CC_SUCCESS) return

      ! Set process-specific name and info
      call this%set_name('seasalt')
      call this%set_version('1.0.0')
      call this%set_description('Process for computing sea salt aerosol emissions over ocean surfaces')

      ! Parse process-specific configuration using unified approach
      call this%parse_process_config(state_manager, error_manager)
      if (error_manager%has_error()) then
         rc = CC_FAILURE
         return
      end if

      ! Get state pointers from state_manager (needed for species loading)
      this%chem_state => state_manager%get_chem_state_ptr()
      this%met_state => state_manager%get_met_state_ptr()
      this%state_manager => state_manager

      ! Load species from ChemState based on is_seasalt property
      call this%process_config%load_species_from_chem_state(this%chem_state, error_manager)
      if (error_manager%has_error()) then
         rc = CC_FAILURE
         return
      end if

      ! Validate the configuration with StateManager
      call this%process_config%validate(state_manager, error_manager)
      if (error_manager%has_error()) then
         rc = CC_FAILURE
         return
      end if

      ! Initialize utility helpers
      call this%unit_converter%init(error_manager)
      if (error_manager%has_error()) then
         rc = CC_FAILURE
         return
      end if

      ! Register diagnostics for this process (only if diagnostics enabled)
      call this%register_diagnostics(state_manager, rc)
      if (rc /= CC_SUCCESS) then
         return
      end if

      ! Allocate diagnostic class members if diagnostics are enabled
      if (this%process_config%seasalt_config%diagnostics) then
         ! Allocate common diagnostic fields (used by all schemes)
         ! Scalar diagnostic
         allocate(this%column_seasalt_mass_emission_total)
         this%column_seasalt_mass_emission_total = 0.0_fp
         ! Scalar diagnostic
         allocate(this%column_seasalt_number_emission_total)
         this%column_seasalt_number_emission_total = 0.0_fp
         
         ! Allocate and initialize scheme-specific diagnostic fields based on selected scheme
         select case (this%process_config%seasalt_config%scheme_name)
         case ("gong97")
            ! Scheme-specific diagnostics for gong97
            ! 1D diagnostic: species only
            if (this%process_config%seasalt_config%n_species > 0) then
               allocate(this%column_seasalt_mass_emission_per_bin(this%process_config%seasalt_config%n_species))
            end if
            if (allocated(this%column_seasalt_mass_emission_per_bin)) this%column_seasalt_mass_emission_per_bin = 0.0_fp
            ! 1D diagnostic: species only
            if (this%process_config%seasalt_config%n_species > 0) then
               allocate(this%column_seasalt_number_emission_per_bin(this%process_config%seasalt_config%n_species))
            end if
            if (allocated(this%column_seasalt_number_emission_per_bin)) this%column_seasalt_number_emission_per_bin = 0.0_fp
         case ("gong03")
            ! Scheme-specific diagnostics for gong03
            ! 1D diagnostic: species only
            if (this%process_config%seasalt_config%n_species > 0) then
               allocate(this%column_seasalt_mass_emission_per_bin(this%process_config%seasalt_config%n_species))
            end if
            if (allocated(this%column_seasalt_mass_emission_per_bin)) this%column_seasalt_mass_emission_per_bin = 0.0_fp
            ! 1D diagnostic: species only
            if (this%process_config%seasalt_config%n_species > 0) then
               allocate(this%column_seasalt_number_emission_per_bin(this%process_config%seasalt_config%n_species))
            end if
            if (allocated(this%column_seasalt_number_emission_per_bin)) this%column_seasalt_number_emission_per_bin = 0.0_fp
         case ("geos12")
            ! Scheme-specific diagnostics for geos12
            ! 1D diagnostic: species only
            if (this%process_config%seasalt_config%n_species > 0) then
               allocate(this%column_seasalt_mass_emission_per_bin(this%process_config%seasalt_config%n_species))
            end if
            if (allocated(this%column_seasalt_mass_emission_per_bin)) this%column_seasalt_mass_emission_per_bin = 0.0_fp
            ! 1D diagnostic: species only
            if (this%process_config%seasalt_config%n_species > 0) then
               allocate(this%column_seasalt_number_emission_per_bin(this%process_config%seasalt_config%n_species))
            end if
            if (allocated(this%column_seasalt_number_emission_per_bin)) this%column_seasalt_number_emission_per_bin = 0.0_fp
         case default
            ! No scheme-specific diagnostics for unknown schemes
         end select
      end if

   end subroutine process_init

   !> Run the seasalt process
   !!
   !! This method implements the main ProcessInterface run method.
   !! For ColumnProcessInterface processes, the actual column iteration is handled
   !! by ProcessManager, so this method serves as a placeholder for any 3D operations
   !! that might be needed before or after column processing.
   subroutine process_run(this, state_manager, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      type(StateManagerType), intent(inout) :: state_manager
      integer, intent(out) :: rc

      rc = CC_SUCCESS

      ! Check if process is active
      if (.not. this%process_config%is_active) then
         return
      end if

      ! For ColumnProcessInterface processes, the ProcessManager handles column iteration
      ! and calls run_column() for each virtual column. This method is mainly a placeholder
      ! for any global 3D operations that need to happen before/after column processing.
      
      ! Currently no global 3D operations needed for seasalt process
      ! All processing happens in run_column() method

   end subroutine process_run

   !> Finalize the seasalt process
   subroutine process_finalize(this, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      integer, intent(out) :: rc

      rc = CC_SUCCESS

      ! Finalize column processing
      call this%finalize_column_processing(rc)
      if (rc /= CC_SUCCESS) return

      ! Deallocate diagnostic class members
      if (allocated(this%column_seasalt_mass_emission_total)) deallocate(this%column_seasalt_mass_emission_total)
      if (allocated(this%column_seasalt_number_emission_total)) deallocate(this%column_seasalt_number_emission_total)
      ! Deallocate scheme-specific diagnostic fields (only deallocate unique fields once)
      if (allocated(this%column_seasalt_mass_emission_per_bin)) deallocate(this%column_seasalt_mass_emission_per_bin)
      if (allocated(this%column_seasalt_number_emission_per_bin)) deallocate(this%column_seasalt_number_emission_per_bin)

      ! Finalize unified configuration
      call this%process_config%finalize()

      ! Call base class finalization (handles common cleanup)
      call this%ColumnProcessInterface%finalize(rc)

   end subroutine process_finalize

   !> Parse process configuration using unified approach
   !! This function bridges the ConfigManager YAML structure to process-specific configuration
   subroutine parse_seasalt_config(this, state_manager, error_manager)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      type(StateManagerType), intent(in) :: state_manager
      type(ErrorManagerType), intent(inout) :: error_manager

      type(ConfigManagerType), pointer :: config_manager

      ! Get configuration manager from state manager
      ! TODO: StateManager needs to provide ConfigManagerType access
      ! For now, this will need to be updated when StateManager interface is enhanced
      ! config_manager => state_manager%get_config_manager()

      ! Use the unified configuration loader from SeaSaltCommon_Mod
      ! This handles the complexity of parsing hierarchical YAML into process-specific types
      call this%process_config%load_from_config(config_manager, error_manager)
      if (error_manager%has_error()) then
         call error_manager%add_context("ProcessSeaSaltInterface", &
            "Failed to parse seasalt process configuration")
         return
      end if

      ! Process is now configured - the unified config contains all scheme-specific settings

   end subroutine parse_seasalt_config

   !========================================================================
   ! Column Processing Interface Implementation
   !========================================================================

   !> Initialize column processing for seasalt
   !!
   !! This method sets up the column processing infrastructure for the process.
   !! The base class ColumnProcessInterface handles the actual column virtualization.
   subroutine init_column_processing(this, state_manager, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      type(StateManagerType), intent(inout) :: state_manager
      integer, intent(out) :: rc

      rc = CC_SUCCESS

      ! Enable column processing and set batch size for optimal performance
      call this%enable_column_processing()
      call this%set_column_batch_size(50)  ! Process 50 columns at a time

      ! Any process-specific column processing setup would go here
      ! For seasalt, no additional setup is needed

   end subroutine init_column_processing

   !> Process a single virtual column for seasalt
   !!
   !! This is the core column processing method where the actual atmospheric process
   !! calculations happen for a single column. The base class handles column
   !! virtualization and calls this method for each virtual column.
   subroutine run_column(this, column, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      type(VirtualColumnType), intent(inout) :: column
      integer, intent(out) :: rc

      rc = CC_SUCCESS

      ! Check if process is active
      if (.not. this%process_config%is_active) return

      ! Delegate to the active scheme for column processing
      call this%run_active_scheme_column(column, rc)

      ! Calculate and update diagnostics if enabled
      if (this%process_config%seasalt_config%diagnostics .and. rc == CC_SUCCESS) then
         call this%calculate_and_update_diagnostics(column, rc)
      end if

   end subroutine run_column

   !> Finalize column processing for seasalt
   !!
   !! Clean up any column processing resources.
   subroutine finalize_column_processing(this, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      integer, intent(out) :: rc

      rc = CC_SUCCESS

      ! Clean up column processing
      call this%disable_column_processing()

      ! Any process-specific cleanup would go here

   end subroutine finalize_column_processing

   !> Get the state manager for base class access to diagnostic infrastructure
   function get_state_manager_impl(this) result(state_manager)
      class(ProcessSeaSaltInterface), intent(in) :: this
      type(StateManagerType), pointer :: state_manager

      state_manager => this%state_manager

   end function get_state_manager_impl

   !> Run the active scheme for a single virtual column
   !!
   !! This method adapts the existing scheme methods to work with virtual columns
   !! instead of state manager column indices.
   subroutine run_active_scheme_column(this, column, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      type(VirtualColumnType), intent(inout) :: column
      integer, intent(out) :: rc

      rc = CC_SUCCESS

      ! Delegate to appropriate scheme using unified config
      select case (trim(this%process_config%seasalt_config%scheme))
      case ('gong97')
         call this%run_gong97_scheme_column(column, rc)
      case ('gong03')
         call this%run_gong03_scheme_column(column, rc)
      case ('geos12')
         call this%run_geos12_scheme_column(column, rc)
      case default
         rc = CC_FAILURE
      end select

   end subroutine run_active_scheme_column

   !> Run the gong97 scheme for a single virtual column
   subroutine run_gong97_scheme_column(this, column, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      type(VirtualColumnType), intent(inout) :: column
      integer, intent(out) :: rc

      ! Local variables for scheme calculation
      type(VirtualMetType), pointer :: met => null()  ! Pointer to meteorological data
      ! Meteorological fields
      real(fp), allocatable :: frocean(:)
      real(fp), allocatable :: frseaice(:)
      real(fp), allocatable :: sst(:)
      real(fp), allocatable :: u10m(:)
      real(fp), allocatable :: v10m(:)
      ! Species properties
      real(fp), allocatable :: species_density(:)
      real(fp), allocatable :: species_radius(:)
      real(fp), allocatable :: species_lower_radius(:)
      real(fp), allocatable :: species_upper_radius(:)
      real(fp), allocatable :: species_conc(:,:)
      real(fp), allocatable :: species_tendencies(:,:)
      integer :: n_species, n_levels, n_chem, n_emis, i, k
      integer, allocatable :: species_indices(:)

      rc = CC_SUCCESS

      ! Get dimensions from virtual column
      n_levels = 1  ! Surface-only processing
      
      ! Get seasalt species information from process configuration
      n_species = this%process_config%seasalt_config%n_species
      if (n_species <= 0) then
         return
      end if
      
      ! Get species indices directly from configuration (pre-computed)
      allocate(species_indices(n_species))
      species_indices(1:n_species) = this%process_config%seasalt_config%species_indices(1:n_species)

      ! Allocate arrays
      allocate(species_conc(1, n_species))
      allocate(species_tendencies(1, n_species))
      ! Allocate meteorological field arrays based on field type and process configuration
      allocate(frocean(1))  ! Surface field - always scalar
      allocate(frseaice(1))  ! Surface field - always scalar
      allocate(sst(1))  ! Surface field - always scalar
      allocate(u10m(1))  ! Surface field - always scalar
      allocate(v10m(1))  ! Surface field - always scalar
      allocate(species_density(n_species), species_radius(n_species), species_lower_radius(n_species), species_upper_radius(n_species))
      species_tendencies = 0.0_fp

      ! Get meteorological data pointer from virtual column (VirtualMet pattern)
      met => column%get_met()

      ! Extract required fields from met pointer based on field type and processing mode
      frocean(1) = met%FROCEAN  ! Surface field - scalar access
      frseaice(1) = met%FRSEAICE  ! Surface field - scalar access
      sst(1) = met%SST  ! Surface field - scalar access
      u10m(1) = met%U10M  ! Surface field - scalar access
      v10m(1) = met%V10M  ! Surface field - scalar access

      ! Get species concentrations from virtual column
      ! Surface-only processing - get surface level concentrations
      do i = 1, n_species
         species_conc(1, i) = column%get_chem_field(species_indices(i), 1)
      end do

      ! Get species properties from configuration (pre-loaded during initialization)
      ! Use species properties from process configuration
      species_density(1:n_species) = this%process_config%seasalt_config%species_density(1:n_species)
      ! Use species properties from process configuration
      species_radius(1:n_species) = this%process_config%seasalt_config%species_radius(1:n_species)
      ! Use species properties from process configuration
      species_lower_radius(1:n_species) = this%process_config%seasalt_config%species_lower_radius(1:n_species)
      ! Use species properties from process configuration
      species_upper_radius(1:n_species) = this%process_config%seasalt_config%species_upper_radius(1:n_species)

      ! Call the science scheme with optional diagnostic parameters
      ! Note: gong97 uses the following diagnostic fields (if diagnostics enabled):
      ! - seasalt_mass_emission_total (Sea salt mass emission flux total)
      ! - seasalt_number_emission_total (Sea salt number emission flux total)
      if (this%process_config%seasalt_config%diagnostics) then
         ! Call with diagnostic outputs enabled
         call compute_gong97( &
            n_levels, &
            n_species, &
            this%process_config%gong97_config, &
            frocean, &
            frseaice, &
            sst, &
            u10m, &
            v10m, &
            species_density, &
            species_radius, &
            species_lower_radius, &
            species_upper_radius, &
            species_conc, &
            species_tendencies, &
            this%column_seasalt_mass_emission_total, &
            this%column_seasalt_number_emission_total, &
            this%column_seasalt_mass_emission_per_bin, &
            this%column_seasalt_number_emission_per_bin &
         )
      else
         ! Call without diagnostic outputs (optional parameters not passed)
         call compute_gong97( &
            n_levels, &
            n_species, &
            this%process_config%gong97_config, &
            frocean, &
            frseaice, &
            sst, &
            u10m, &
            v10m, &
            species_density, &
            species_radius, &
            species_lower_radius, &
            species_upper_radius, &
            species_conc, &
            species_tendencies &
         )
      end if

      ! Apply tendencies back to virtual column
      ! Surface-only processing - apply tendencies to surface level only
      do i = 1, n_species
         call column%set_chem_field(1, species_indices(i), &
                                   species_conc(1, i) + species_tendencies(1, i))
      end do

   end subroutine run_gong97_scheme_column

   !> Run the gong03 scheme for a single virtual column
   subroutine run_gong03_scheme_column(this, column, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      type(VirtualColumnType), intent(inout) :: column
      integer, intent(out) :: rc

      ! Local variables for scheme calculation
      type(VirtualMetType), pointer :: met => null()  ! Pointer to meteorological data
      ! Meteorological fields
      real(fp), allocatable :: frocean(:)
      real(fp), allocatable :: frseaice(:)
      real(fp), allocatable :: sst(:)
      real(fp), allocatable :: u10m(:)
      real(fp), allocatable :: v10m(:)
      ! Species properties
      real(fp), allocatable :: species_density(:)
      real(fp), allocatable :: species_radius(:)
      real(fp), allocatable :: species_lower_radius(:)
      real(fp), allocatable :: species_upper_radius(:)
      real(fp), allocatable :: species_conc(:,:)
      real(fp), allocatable :: species_tendencies(:,:)
      integer :: n_species, n_levels, n_chem, n_emis, i, k
      integer, allocatable :: species_indices(:)

      rc = CC_SUCCESS

      ! Get dimensions from virtual column
      n_levels = 1  ! Surface-only processing
      
      ! Get seasalt species information from process configuration
      n_species = this%process_config%seasalt_config%n_species
      if (n_species <= 0) then
         return
      end if
      
      ! Get species indices directly from configuration (pre-computed)
      allocate(species_indices(n_species))
      species_indices(1:n_species) = this%process_config%seasalt_config%species_indices(1:n_species)

      ! Allocate arrays
      allocate(species_conc(1, n_species))
      allocate(species_tendencies(1, n_species))
      ! Allocate meteorological field arrays based on field type and process configuration
      allocate(frocean(1))  ! Surface field - always scalar
      allocate(frseaice(1))  ! Surface field - always scalar
      allocate(sst(1))  ! Surface field - always scalar
      allocate(u10m(1))  ! Surface field - always scalar
      allocate(v10m(1))  ! Surface field - always scalar
      allocate(species_density(n_species), species_radius(n_species), species_lower_radius(n_species), species_upper_radius(n_species))
      species_tendencies = 0.0_fp

      ! Get meteorological data pointer from virtual column (VirtualMet pattern)
      met => column%get_met()

      ! Extract required fields from met pointer based on field type and processing mode
      frocean(1) = met%FROCEAN  ! Surface field - scalar access
      frseaice(1) = met%FRSEAICE  ! Surface field - scalar access
      sst(1) = met%SST  ! Surface field - scalar access
      u10m(1) = met%U10M  ! Surface field - scalar access
      v10m(1) = met%V10M  ! Surface field - scalar access

      ! Get species concentrations from virtual column
      ! Surface-only processing - get surface level concentrations
      do i = 1, n_species
         species_conc(1, i) = column%get_chem_field(species_indices(i), 1)
      end do

      ! Get species properties from configuration (pre-loaded during initialization)
      ! Use species properties from process configuration
      species_density(1:n_species) = this%process_config%seasalt_config%species_density(1:n_species)
      ! Use species properties from process configuration
      species_radius(1:n_species) = this%process_config%seasalt_config%species_radius(1:n_species)
      ! Use species properties from process configuration
      species_lower_radius(1:n_species) = this%process_config%seasalt_config%species_lower_radius(1:n_species)
      ! Use species properties from process configuration
      species_upper_radius(1:n_species) = this%process_config%seasalt_config%species_upper_radius(1:n_species)

      ! Call the science scheme with optional diagnostic parameters
      ! Note: gong03 uses the following diagnostic fields (if diagnostics enabled):
      ! - seasalt_mass_emission_total (Sea salt mass emission flux total)
      ! - seasalt_number_emission_total (Sea salt number emission flux total)
      if (this%process_config%seasalt_config%diagnostics) then
         ! Call with diagnostic outputs enabled
         call compute_gong03( &
            n_levels, &
            n_species, &
            this%process_config%gong03_config, &
            frocean, &
            frseaice, &
            sst, &
            u10m, &
            v10m, &
            species_density, &
            species_radius, &
            species_lower_radius, &
            species_upper_radius, &
            species_conc, &
            species_tendencies, &
            this%column_seasalt_mass_emission_total, &
            this%column_seasalt_number_emission_total, &
            this%column_seasalt_mass_emission_per_bin, &
            this%column_seasalt_number_emission_per_bin &
         )
      else
         ! Call without diagnostic outputs (optional parameters not passed)
         call compute_gong03( &
            n_levels, &
            n_species, &
            this%process_config%gong03_config, &
            frocean, &
            frseaice, &
            sst, &
            u10m, &
            v10m, &
            species_density, &
            species_radius, &
            species_lower_radius, &
            species_upper_radius, &
            species_conc, &
            species_tendencies &
         )
      end if

      ! Apply tendencies back to virtual column
      ! Surface-only processing - apply tendencies to surface level only
      do i = 1, n_species
         call column%set_chem_field(1, species_indices(i), &
                                   species_conc(1, i) + species_tendencies(1, i))
      end do

   end subroutine run_gong03_scheme_column

   !> Run the geos12 scheme for a single virtual column
   subroutine run_geos12_scheme_column(this, column, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      type(VirtualColumnType), intent(inout) :: column
      integer, intent(out) :: rc

      ! Local variables for scheme calculation
      type(VirtualMetType), pointer :: met => null()  ! Pointer to meteorological data
      ! Meteorological fields
      real(fp), allocatable :: frocean(:)
      real(fp), allocatable :: frseaice(:)
      real(fp), allocatable :: sst(:)
      real(fp), allocatable :: ustar(:)
      ! Species properties
      real(fp), allocatable :: species_density(:)
      real(fp), allocatable :: species_radius(:)
      real(fp), allocatable :: species_lower_radius(:)
      real(fp), allocatable :: species_upper_radius(:)
      real(fp), allocatable :: species_conc(:,:)
      real(fp), allocatable :: species_tendencies(:,:)
      integer :: n_species, n_levels, n_chem, n_emis, i, k
      integer, allocatable :: species_indices(:)

      rc = CC_SUCCESS

      ! Get dimensions from virtual column
      n_levels = 1  ! Surface-only processing
      
      ! Get seasalt species information from process configuration
      n_species = this%process_config%seasalt_config%n_species
      if (n_species <= 0) then
         return
      end if
      
      ! Get species indices directly from configuration (pre-computed)
      allocate(species_indices(n_species))
      species_indices(1:n_species) = this%process_config%seasalt_config%species_indices(1:n_species)

      ! Allocate arrays
      allocate(species_conc(1, n_species))
      allocate(species_tendencies(1, n_species))
      ! Allocate meteorological field arrays based on field type and process configuration
      allocate(frocean(1))  ! Surface field - always scalar
      allocate(frseaice(1))  ! Surface field - always scalar
      allocate(sst(1))  ! Surface field - always scalar
      allocate(ustar(1))  ! Surface field - always scalar
      allocate(species_density(n_species), species_radius(n_species), species_lower_radius(n_species), species_upper_radius(n_species))
      species_tendencies = 0.0_fp

      ! Get meteorological data pointer from virtual column (VirtualMet pattern)
      met => column%get_met()

      ! Extract required fields from met pointer based on field type and processing mode
      frocean(1) = met%FROCEAN  ! Surface field - scalar access
      frseaice(1) = met%FRSEAICE  ! Surface field - scalar access
      sst(1) = met%SST  ! Surface field - scalar access
      ustar(1) = met%USTAR  ! Surface field - scalar access

      ! Get species concentrations from virtual column
      ! Surface-only processing - get surface level concentrations
      do i = 1, n_species
         species_conc(1, i) = column%get_chem_field(species_indices(i), 1)
      end do

      ! Get species properties from configuration (pre-loaded during initialization)
      ! Use species properties from process configuration
      species_density(1:n_species) = this%process_config%seasalt_config%species_density(1:n_species)
      ! Use species properties from process configuration
      species_radius(1:n_species) = this%process_config%seasalt_config%species_radius(1:n_species)
      ! Use species properties from process configuration
      species_lower_radius(1:n_species) = this%process_config%seasalt_config%species_lower_radius(1:n_species)
      ! Use species properties from process configuration
      species_upper_radius(1:n_species) = this%process_config%seasalt_config%species_upper_radius(1:n_species)

      ! Call the science scheme with optional diagnostic parameters
      ! Note: geos12 uses the following diagnostic fields (if diagnostics enabled):
      ! - seasalt_mass_emission_total (Sea salt mass emission flux total)
      ! - seasalt_number_emission_total (Sea salt number emission flux total)
      if (this%process_config%seasalt_config%diagnostics) then
         ! Call with diagnostic outputs enabled
         call compute_geos12( &
            n_levels, &
            n_species, &
            this%process_config%geos12_config, &
            frocean, &
            frseaice, &
            sst, &
            ustar, &
            species_density, &
            species_radius, &
            species_lower_radius, &
            species_upper_radius, &
            species_conc, &
            species_tendencies, &
            this%column_seasalt_mass_emission_total, &
            this%column_seasalt_number_emission_total, &
            this%column_seasalt_mass_emission_per_bin, &
            this%column_seasalt_number_emission_per_bin &
         )
      else
         ! Call without diagnostic outputs (optional parameters not passed)
         call compute_geos12( &
            n_levels, &
            n_species, &
            this%process_config%geos12_config, &
            frocean, &
            frseaice, &
            sst, &
            ustar, &
            species_density, &
            species_radius, &
            species_lower_radius, &
            species_upper_radius, &
            species_conc, &
            species_tendencies &
         )
      end if

      ! Apply tendencies back to virtual column
      ! Surface-only processing - apply tendencies to surface level only
      do i = 1, n_species
         call column%set_chem_field(1, species_indices(i), &
                                   species_conc(1, i) + species_tendencies(1, i))
      end do

   end subroutine run_geos12_scheme_column



   !> Get required meteorological fields for this process
   function get_required_met_fields(this) result(field_names)
      class(ProcessSeaSaltInterface), intent(in) :: this
      character(len=64), allocatable :: field_names(:)

      ! Get scheme-specific fields based on selected scheme
      select case (trim(this%process_config%seasalt_config%scheme))
      case ('gong97')
         allocate(field_names(5))
         field_names(1) = 'FROCEAN'
         field_names(2) = 'FRSEAICE'
         field_names(3) = 'SST'
         field_names(4) = 'U10M'
         field_names(5) = 'V10M'
      case ('gong03')
         allocate(field_names(5))
         field_names(1) = 'FROCEAN'
         field_names(2) = 'FRSEAICE'
         field_names(3) = 'SST'
         field_names(4) = 'U10M'
         field_names(5) = 'V10M'
      case ('geos12')
         allocate(field_names(4))
         field_names(1) = 'FROCEAN'
         field_names(2) = 'FRSEAICE'
         field_names(3) = 'SST'
         field_names(4) = 'USTAR'
      case default
         allocate(field_names(0))
      end select

   end function get_required_met_fields

   !> Get required diagnostic fields for this process
   function get_required_diagnostic_fields(this) result(field_names)
      class(ProcessSeaSaltInterface), intent(in) :: this
      character(len=64), allocatable :: field_names(:)

      allocate(field_names(2))
      field_names(1) = 'seasalt_mass_emission_total'
      field_names(2) = 'seasalt_number_emission_total'

   end function get_required_diagnostic_fields

   !> Register diagnostic fields with the DiagnosticManager

   subroutine register_process_diagnostics(this, container, rc)
      use DiagnosticInterface_Mod, only: DiagnosticRegistryType, DIAG_REAL_2D, DIAG_REAL_3D
      
      class(ProcessSeaSaltInterface), intent(inout) :: this
      type(StateManagerType), intent(inout) :: container
      integer, intent(out) :: rc
      
      type(DiagnosticManagerType), pointer :: diag_mgr
      type(DiagnosticRegistryType), pointer :: registry
      type(GridManagerType), pointer :: grid_mgr
      character(len=32) :: selected_scheme
      integer :: nx, ny, n_species      integer :: dims_2d(2)
      integer :: dims_3d_species(3)
      
      rc = CC_SUCCESS
      
      ! Only register diagnostics if enabled in config
      if (.not. this%process_config%seasalt_config%diagnostics) then
         return
      endif
      
      ! Get managers
      diag_mgr => container%get_diagnostic_manager()
      grid_mgr => container%get_grid_manager()
      
      ! Register this process with diagnostic manager (only once per process)
      call diag_mgr%register_process('seasalt', container, rc)
      if (rc /= CC_SUCCESS) return
      
      ! Get the process registry for registering individual diagnostics
      call diag_mgr%get_process_registry('seasalt', registry, rc)
      if (rc /= CC_SUCCESS) return
      
      ! Get grid dimensions
      nx = grid_mgr%geometry%get_nx()
      ny = grid_mgr%geometry%get_ny()
      dims_2d = [nx, ny]
      
      ! Get species count for 3D diagnostics
      n_species = this%process_config%seasalt_config%n_species
      dims_3d_species = [nx, ny, n_species]
      
      ! Register seasalt_mass_emission_total
      call this%register_diagnostic_field(registry, 'seasalt_mass_emission_total', &
                                          'Sea salt mass emission flux total', &
                                          'ug/m2/s', DIAG_REAL_2D, &
                                          'seasalt', dims_2d, rc)
      if (rc /= CC_SUCCESS) return
      
      ! Register seasalt_number_emission_total
      call this%register_diagnostic_field(registry, 'seasalt_number_emission_total', &
                                          'Sea salt number emission flux total', &
                                          '#/m2/s', DIAG_REAL_2D, &
                                          'seasalt', dims_2d, rc)
      if (rc /= CC_SUCCESS) return
      
      ! Get selected scheme
      selected_scheme = trim(this%process_config%seasalt_config%scheme)
      
      ! Register scheme-specific diagnostics based on selected scheme
      select case (selected_scheme)
      
      case ('gong97')
         ! Register gong97-specific diagnostics
         call this%register_diagnostic_field(registry, 'seasalt_mass_emission_per_bin', &
                                             'Sea salt mass emission flux per bin', &
                                             'ug/m2/s', DIAG_REAL_3D, &
                                             'seasalt', dims_3d_species, rc)
         if (rc /= CC_SUCCESS) return
         
         call this%register_diagnostic_field(registry, 'seasalt_number_emission_per_bin', &
                                             'Sea salt number emission flux per bin', &
                                             '#/m2/s', DIAG_REAL_3D, &
                                             'seasalt', dims_3d_species, rc)
         if (rc /= CC_SUCCESS) return
         
      case ('gong03')
         ! Register gong03-specific diagnostics
         call this%register_diagnostic_field(registry, 'seasalt_mass_emission_per_bin', &
                                             'Sea salt mass emission flux per bin', &
                                             'ug/m2/s', DIAG_REAL_3D, &
                                             'seasalt', dims_3d_species, rc)
         if (rc /= CC_SUCCESS) return
         
         call this%register_diagnostic_field(registry, 'seasalt_number_emission_per_bin', &
                                             'Sea salt number emission flux per bin', &
                                             '#/m2/s', DIAG_REAL_3D, &
                                             'seasalt', dims_3d_species, rc)
         if (rc /= CC_SUCCESS) return
         
      case ('geos12')
         ! Register geos12-specific diagnostics
         call this%register_diagnostic_field(registry, 'seasalt_mass_emission_per_bin', &
                                             'Sea salt mass emission flux per bin', &
                                             'ug/m2/s', DIAG_REAL_3D, &
                                             'seasalt', dims_3d_species, rc)
         if (rc /= CC_SUCCESS) return
         
         call this%register_diagnostic_field(registry, 'seasalt_number_emission_per_bin', &
                                             'Sea salt number emission flux per bin', &
                                             '#/m2/s', DIAG_REAL_3D, &
                                             'seasalt', dims_3d_species, rc)
         if (rc /= CC_SUCCESS) return
         
      case default
         ! Unknown scheme - only register common diagnostics
         ! (already done above)
         
      end select

   end subroutine register_process_diagnostics

   !> Calculate and update all diagnostic fields for this process
   !! 
   !! With the new flexible column-level design, diagnostics are calculated directly by the 
   !! science schemes for each column and passed to this method for aggregation or output.
   !! This approach uses dimension inference to reduce 2D->scalar and 3D->1D for column processing.
   subroutine calculate_and_update_diagnostics(this, column, rc)
      class(ProcessSeaSaltInterface), intent(inout) :: this
      type(VirtualColumnType), intent(in) :: column
      integer, intent(out) :: rc
      
      integer :: i_col, j_col  ! Column grid position
      character(len=64) :: selected_scheme
      
      rc = CC_SUCCESS
      
      ! Skip if diagnostics not enabled
      if (.not. this%process_config%seasalt_config%diagnostics) return
      
      ! Get column grid position (x, y indices)
      i_col = column%get_i_index()
      j_col = column%get_j_index()
      
      ! Update common diagnostic fields (used by all schemes)
      ! Scalar diagnostic field
      call this%update_column_diagnostics('seasalt_mass_emission_total', &
                                          this%column_seasalt_mass_emission_total, &
                                          i_col, j_col, rc)
      if (rc /= CC_SUCCESS) return
      
      ! Scalar diagnostic field
      call this%update_column_diagnostics('seasalt_number_emission_total', &
                                          this%column_seasalt_number_emission_total, &
                                          i_col, j_col, rc)
      if (rc /= CC_SUCCESS) return
      
      ! Update scheme-specific diagnostic fields based on active scheme
      selected_scheme = trim(this%process_config%seasalt_config%scheme)
      
      select case (selected_scheme)
      case ("gong97")
         ! Update 1D diagnostics (map to 3D global fields)
         if (allocated(this%column_seasalt_mass_emission_per_bin)) then
            call this%update_column_diagnostics('seasalt_mass_emission_per_bin', &
                                                this%column_seasalt_mass_emission_per_bin, &
                                                i_col, j_col, rc)
            if (rc /= CC_SUCCESS) return
         end if
         
         ! Update 1D diagnostics (map to 3D global fields)
         if (allocated(this%column_seasalt_number_emission_per_bin)) then
            call this%update_column_diagnostics('seasalt_number_emission_per_bin', &
                                                this%column_seasalt_number_emission_per_bin, &
                                                i_col, j_col, rc)
            if (rc /= CC_SUCCESS) return
         end if
         
      case ("gong03")
         ! Update 1D diagnostics (map to 3D global fields)
         if (allocated(this%column_seasalt_mass_emission_per_bin)) then
            call this%update_column_diagnostics('seasalt_mass_emission_per_bin', &
                                                this%column_seasalt_mass_emission_per_bin, &
                                                i_col, j_col, rc)
            if (rc /= CC_SUCCESS) return
         end if
         
         ! Update 1D diagnostics (map to 3D global fields)
         if (allocated(this%column_seasalt_number_emission_per_bin)) then
            call this%update_column_diagnostics('seasalt_number_emission_per_bin', &
                                                this%column_seasalt_number_emission_per_bin, &
                                                i_col, j_col, rc)
            if (rc /= CC_SUCCESS) return
         end if
         
      case ("geos12")
         ! Update 1D diagnostics (map to 3D global fields)
         if (allocated(this%column_seasalt_mass_emission_per_bin)) then
            call this%update_column_diagnostics('seasalt_mass_emission_per_bin', &
                                                this%column_seasalt_mass_emission_per_bin, &
                                                i_col, j_col, rc)
            if (rc /= CC_SUCCESS) return
         end if
         
         ! Update 1D diagnostics (map to 3D global fields)
         if (allocated(this%column_seasalt_number_emission_per_bin)) then
            call this%update_column_diagnostics('seasalt_number_emission_per_bin', &
                                                this%column_seasalt_number_emission_per_bin, &
                                                i_col, j_col, rc)
            if (rc /= CC_SUCCESS) return
         end if
         
      end select
      
   end subroutine calculate_and_update_diagnostics


end module ProcessSeaSaltInterface_Mod