MODULE MODULE_CHEMVARS

use catchem_constants, only : kind_chem
use catchem_config, only : epsilc

   IMPLICIT NONE

!
! the next are variables that chemdriver will need
!
   !REAL(kind=kind_chem), PARAMETER             :: epsilc = 1.e-30
!  INTEGER, PARAMETER          :: num_emis_ant = 9
   INTEGER, PARAMETER          :: num_emis_dust = 5
   INTEGER, PARAMETER          :: num_emis_seas = 5
   INTEGER, PARAMETER          :: ne_area = 41
   INTEGER, PARAMETER          :: nmegan = 1
!   INTEGER, PARAMETER          :: kemit = 1
   INTEGER                     :: stepbioe,stepfirepl
   REAL(kind=kind_chem), ALLOCATABLE :: chem( :, :, :, : )
   REAL(kind=kind_chem), ALLOCATABLE :: emis_ant( :, :, :,:)
   REAL(kind=kind_chem), ALLOCATABLE :: emis_vol( :, :, :,:)
   REAL(kind=kind_chem), ALLOCATABLE :: relhum( :, :, : )
   REAL(kind=kind_chem), ALLOCATABLE :: e_bio( :, :, : )
   REAL(kind=kind_chem), ALLOCATABLE :: dms_0( :, :)
   REAL(kind=kind_chem), ALLOCATABLE :: ttday( :, :)
   REAL(kind=kind_chem), ALLOCATABLE :: tcosz( :, :)
   REAL(kind=kind_chem), ALLOCATABLE :: erod( :, :,:)
   REAL(kind=kind_chem), ALLOCATABLE :: emis_dust( :, :, :,:)
   REAL(kind=kind_chem), ALLOCATABLE :: srce_dust( :, :, :,:) 
   REAL(kind=kind_chem), ALLOCATABLE :: emis_seas( :, :, :,:)
   REAL(kind=kind_chem), ALLOCATABLE :: backg_oh( :, :, : )
   REAL(kind=kind_chem), ALLOCATABLE :: backg_h2o2( :, :, : )
   REAL(kind=kind_chem), ALLOCATABLE :: backg_no3( :, :, : )
   REAL(kind=kind_chem), ALLOCATABLE :: oh_t( :, :, : )
   REAL(kind=kind_chem), ALLOCATABLE :: h2o2_t( :, :, : )
   REAL(kind=kind_chem), ALLOCATABLE :: no3_t( :, :, : )
   REAL(kind=kind_chem), ALLOCATABLE :: ebu_in(  :, :, : )
   REAL(kind=kind_chem), ALLOCATABLE :: ebu( :, :, :, : )
   REAL(kind=kind_chem), ALLOCATABLE :: mean_fct_agtf( :,  : )
   REAL(kind=kind_chem), ALLOCATABLE :: mean_fct_agef( :,  : )
   REAL(kind=kind_chem), ALLOCATABLE :: mean_fct_agsv( :,  : )
   REAL(kind=kind_chem), ALLOCATABLE :: mean_fct_aggr( :,  : )
   REAL(kind=kind_chem), ALLOCATABLE :: firesize_agtf( :,  : )
   REAL(kind=kind_chem), ALLOCATABLE :: firesize_agef( :,  : )
   REAL(kind=kind_chem), ALLOCATABLE :: firesize_agsv( :,  : )
   REAL(kind=kind_chem), ALLOCATABLE :: firesize_aggr( :,  : )
   REAL(kind=kind_chem), ALLOCATABLE :: ash_fall( :,  : )
   REAL(kind=kind_chem), ALLOCATABLE :: dust_fall( :,  : )
   REAL(kind=kind_chem), ALLOCATABLE :: pm2_5_dry( : , : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: pm2_5_water( : , : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: aerwrf( : , : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: pm2_5_dry_ec( : , : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: pm10( : , : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: sebio_iso( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: sebio_oli( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: sebio_api( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: sebio_lim( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: sebio_xyl( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: sebio_hc3( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: sebio_ete( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: sebio_olt( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: sebio_ket( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: sebio_ald( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: sebio_hcho( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: sebio_eth( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: sebio_ora2( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: sebio_co( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: sebio_nr( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: noag_grow( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: noag_nongrow( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: nononag( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: slai( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: ebio_iso( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: ebio_oli( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: ebio_api( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: ebio_lim( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: ebio_xyl( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: ebio_hc3( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: ebio_ete( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: ebio_olt( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: ebio_ket( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: ebio_ald( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: ebio_hcho( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: ebio_eth( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: ebio_ora2( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: ebio_co( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: ebio_nr( : , : )
   REAL(kind=kind_chem), ALLOCATABLE :: ebio_no( : , : )

   !shc stuff for MEGAN v2.04

   real(kind=kind_chem), ALLOCATABLE :: EFmegan(:, : , :)


   real(kind=kind_chem), ALLOCATABLE :: msebio_isop(:, : )
   real(kind=kind_chem), ALLOCATABLE :: pftp_bt(:, : )
   real(kind=kind_chem), ALLOCATABLE :: pftp_nt(:, : )
   real(kind=kind_chem), ALLOCATABLE :: pftp_sb(:, : )
   real(kind=kind_chem), ALLOCATABLE :: pftp_hb(:, : )

   real(kind=kind_chem), ALLOCATABLE :: mlai(:, :, : )
   real(kind=kind_chem), ALLOCATABLE :: mtsa(:, :, : )
   real(kind=kind_chem), ALLOCATABLE :: mswdown(:, :, : )

   real(kind=kind_chem), ALLOCATABLE :: mebio_isop(:, : )
   real(kind=kind_chem), ALLOCATABLE :: mebio_apin(:, : )
   real(kind=kind_chem), ALLOCATABLE :: mebio_bpin(:, : )
   real(kind=kind_chem), ALLOCATABLE :: mebio_bcar(:, : )
   real(kind=kind_chem), ALLOCATABLE :: mebio_acet(:, : )
   real(kind=kind_chem), ALLOCATABLE :: mebio_mbo(:, : )
   real(kind=kind_chem), ALLOCATABLE :: mebio_no(:, : )
!
! stuff for optical driver
!
! next three are for feedback to physics
!
   REAL(kind=kind_chem), ALLOCATABLE :: extt( :, :, :, : )
   REAL(kind=kind_chem), ALLOCATABLE :: ssca( :, :, :, : )
   REAL(kind=kind_chem), ALLOCATABLE :: asympar( :, :, :, : )
!
! output diagnosics
!
   REAL(kind=kind_chem), ALLOCATABLE :: aod( :,: )
   REAL(kind=kind_chem), ALLOCATABLE :: ext_coeff( :, :, :,:)
   REAL(kind=kind_chem), ALLOCATABLE :: bscat_coeff( :, :, :,:)
   REAL(kind=kind_chem), ALLOCATABLE :: asym_par( :, :, :,:)
!
! optical calculations, necessary for feedback to physics and diagnostics
   real(kind=kind_chem), ALLOCATABLE :: tauaersw(:, : , :, : )
   real(kind=kind_chem), ALLOCATABLE :: tauaerlw(:, : , :, : )
   real(kind=kind_chem), ALLOCATABLE :: bscoefsw(:, : , :, : )
   real(kind=kind_chem), ALLOCATABLE :: gaersw(:, : , :, : )
   real(kind=kind_chem), ALLOCATABLE :: waersw(:, : , :, : )
   real(kind=kind_chem), ALLOCATABLE :: tauaer1(:, : , : )
   real(kind=kind_chem), ALLOCATABLE :: tauaer2(:, : , : )
   real(kind=kind_chem), ALLOCATABLE :: tauaer3(:, : , : )
   real(kind=kind_chem), ALLOCATABLE :: tauaer4(:, : , : )
   real(kind=kind_chem), ALLOCATABLE :: gaer1(:, : , : )
   real(kind=kind_chem), ALLOCATABLE :: gaer2(:, : , : )
   real(kind=kind_chem), ALLOCATABLE :: gaer3(:, : , : )
   real(kind=kind_chem), ALLOCATABLE :: gaer4(:, : , : )
   real(kind=kind_chem), ALLOCATABLE :: waer1(:, : , : )
   real(kind=kind_chem), ALLOCATABLE :: waer2(:, : , : )
   real(kind=kind_chem), ALLOCATABLE :: waer3(:, : , : )
   real(kind=kind_chem), ALLOCATABLE :: waer4(:, : , : )
   real(kind=kind_chem), ALLOCATABLE :: bscoef1(:, : , : )
   real(kind=kind_chem), ALLOCATABLE :: bscoef2(:, : , : )
   real(kind=kind_chem), ALLOCATABLE :: bscoef3(:, : , : )
   real(kind=kind_chem), ALLOCATABLE :: bscoef4(:, : , : )
   real(kind=kind_chem), ALLOCATABLE :: l2aer(:, : , : , : )
   real(kind=kind_chem), ALLOCATABLE :: l3aer(:, : , : , : )
   real(kind=kind_chem), ALLOCATABLE :: l4aer(:, : , : , : )
   real(kind=kind_chem), ALLOCATABLE :: l5aer(:, : , : , : )
   real(kind=kind_chem), ALLOCATABLE :: l6aer(:, : , : , : )
   real(kind=kind_chem), ALLOCATABLE :: l7aer(:, : , : , : )
!
! photolysis
!
   real(kind=kind_chem), ALLOCATABLE   :: ph_o31d(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_o33p(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_no2(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_no3o2(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_no3o(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_hno2(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_hno3(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_hno4(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_h2o2(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_ch2or(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_ch2om(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_ch3cho(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_ch3coch3(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_ch3coc2h5(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_hcocho(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_ch3cocho(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_hcochest(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_ch3o2h(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_ch3coo2h(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_ch3ono2(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_hcochob(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_macr(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_n2o5(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_o2(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_pan(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_acet(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_mglo(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   :: ph_hno4_2(:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_n2o (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_pooh (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_mpan (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_mvk (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_etooh (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_prooh (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_onitr (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_acetol (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_glyald (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_hyac (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_mek (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_open (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_gly (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_acetp (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_xooh (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_isooh (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_alkooh (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_mekooh (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_tolooh (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_terpooh (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_cl2 (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_hocl (:, : , : )
   real(kind=kind_chem), ALLOCATABLE   ::ph_fmcl (:, : , : )
!
! stuff for more complpex aerosols and gas phase chem
!
real(kind=kind_chem) ,ALLOCATABLE   :: h2oaj(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: h2oai(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: nu3(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: ac3(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: cor3(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: asulf(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: ahno3(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: anh3(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: cvaro1(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: cvaro2(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: cvalk1(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: cvole1(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: cvapi1(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: cvapi2(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: cvlim1(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: cvlim2(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: mob(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: cvasoaX(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: cvasoa1(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: cvasoa2(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: cvasoa3(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: cvasoa4(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: cvbsoaX(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: cvbsoa1(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: cvbsoa2(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: cvbsoa3(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: cvbsoa4(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: asoa1j(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: asoa1i(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: asoa2j(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: asoa2i(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: asoa3j(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: asoa3i(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: asoa4j(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: asoa4i(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: bsoa1j(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: bsoa1i(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: bsoa2j(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: bsoa2i(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: bsoa3j(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: bsoa3i(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: bsoa4j(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: bsoa4i(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: addt(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: addx(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: addc(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: etep(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: oltp(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: olip(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: cslp(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: limp(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: hc5p(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: hc8p(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: tolp(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: xylp(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: apip(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: isop(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: hc3p(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: ethp(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: o3p(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: tco3(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: mo2(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: o1d(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: olnn(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: olnd(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: rpho(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: xo2(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: ketp(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: xno2(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: ol2p(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: oln(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: macp(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: hocoo(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: bzno2_o(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: bz_o(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: tbu_o(:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: vprm_in(:,:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: rad_vprm(:)
real(kind=kind_chem) ,ALLOCATABLE   :: lambda_vprm(:)
real(kind=kind_chem) ,ALLOCATABLE   :: alpha_vprm(:)
real(kind=kind_chem) ,ALLOCATABLE   :: resp_vprm(:)
real(kind=kind_chem) ,ALLOCATABLE   :: wet_in(:,:,:,:)
real(kind=kind_chem) ,ALLOCATABLE   :: biomt_par(:)
real(kind=kind_chem) ,ALLOCATABLE   :: emit_par(:)


END MODULE MODULE_CHEMVARS
